//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface FestivalLiveInfo : NSObject
{
    _Bool _isOpen;
    NSString *_thumbUrl;
    NSString *_title;
    NSString *_subTitle;
    long long _onLineNum;
    long long _friendWatchedNum;
}

- (void).cxx_destruct;
@property(nonatomic) long long friendWatchedNum; // @synthesize friendWatchedNum=_friendWatchedNum;
@property(nonatomic) long long onLineNum; // @synthesize onLineNum=_onLineNum;
@property(retain, nonatomic) NSString *subTitle; // @synthesize subTitle=_subTitle;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *thumbUrl; // @synthesize thumbUrl=_thumbUrl;
@property(nonatomic) _Bool isOpen; // @synthesize isOpen=_isOpen;

@end

