//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class BaseResponse, FestivalWishConfig, NSData, NSMutableArray, NSString;

@interface FestivalWishHeartbeatResp : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) BaseResponse *baseResponse; // @dynamic baseResponse;
@property(retain, nonatomic) FestivalWishConfig *config; // @dynamic config;
@property(retain, nonatomic) NSData *context; // @dynamic context;
@property(nonatomic) double dataDensity; // @dynamic dataDensity;
@property(retain, nonatomic) NSString *datamd5; // @dynamic datamd5;
@property(retain, nonatomic) NSString *dataurl; // @dynamic dataurl;
@property(retain, nonatomic) NSMutableArray *friendwishlist; // @dynamic friendwishlist;
@property(nonatomic) _Bool hasmore; // @dynamic hasmore;
@property(retain, nonatomic) NSMutableArray *msglist; // @dynamic msglist;
@property(retain, nonatomic) NSMutableArray *musiclist; // @dynamic musiclist;
@property(retain, nonatomic) NSMutableArray *mywishlist; // @dynamic mywishlist;
@property(retain, nonatomic) NSMutableArray *recommendWishlist; // @dynamic recommendWishlist;
@property(retain, nonatomic) NSMutableArray *titlePollWording; // @dynamic titlePollWording;
@property(retain, nonatomic) NSMutableArray *topiclist; // @dynamic topiclist;
@property(nonatomic) unsigned int unused; // @dynamic unused;

@end

