//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class NSData, NSString;

@interface FestivalWishLikeMsg : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned int createtime; // @dynamic createtime;
@property(retain, nonatomic) NSData *finderContact; // @dynamic finderContact;
@property(retain, nonatomic) NSString *hashusername; // @dynamic hashusername;
@property(nonatomic) _Bool haswish; // @dynamic haswish;
@property(retain, nonatomic) NSString *headimgurl; // @dynamic headimgurl;
@property(retain, nonatomic) NSString *nickname; // @dynamic nickname;
@property(retain, nonatomic) NSString *ticket; // @dynamic ticket;
@property(retain, nonatomic) NSString *wishTicket; // @dynamic wishTicket;
@property(retain, nonatomic) NSString *wishid; // @dynamic wishid;

@end

