//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class FestivalWishColor, NSData, NSString;

@interface FestivalWish : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned int action; // @dynamic action;
@property(retain, nonatomic) NSString *city; // @dynamic city;
@property(retain, nonatomic) FestivalWishColor *color; // @dynamic color;
@property(retain, nonatomic) NSString *country; // @dynamic country;
@property(nonatomic) unsigned int createtime; // @dynamic createtime;
@property(retain, nonatomic) NSString *dataaeskey; // @dynamic dataaeskey;
@property(retain, nonatomic) NSString *datamd5; // @dynamic datamd5;
@property(nonatomic) unsigned int datasize; // @dynamic datasize;
@property(nonatomic) unsigned int datatype; // @dynamic datatype;
@property(retain, nonatomic) NSString *dataurl; // @dynamic dataurl;
@property(nonatomic) unsigned int delflag; // @dynamic delflag;
@property(retain, nonatomic) NSData *finderContact; // @dynamic finderContact;
@property(retain, nonatomic) NSString *hashusername; // @dynamic hashusername;
@property(retain, nonatomic) NSString *headimgurl; // @dynamic headimgurl;
@property(nonatomic) unsigned int likecount; // @dynamic likecount;
@property(retain, nonatomic) NSString *liveEncUsername; // @dynamic liveEncUsername;
@property(retain, nonatomic) NSString *nickname; // @dynamic nickname;
@property(retain, nonatomic) NSString *province; // @dynamic province;
@property(nonatomic) unsigned int sex; // @dynamic sex;
@property(retain, nonatomic) NSString *text; // @dynamic text;
@property(retain, nonatomic) NSString *thumburl; // @dynamic thumburl;
@property(retain, nonatomic) NSString *topic; // @dynamic topic;
@property(retain, nonatomic) NSString *username; // @dynamic username;
@property(retain, nonatomic) NSString *wishid; // @dynamic wishid;
@property(nonatomic) int x; // @dynamic x;
@property(nonatomic) int y; // @dynamic y;

@end

