//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class NSString;

@interface FestivalWishConfig : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned int animateInterval; // @dynamic animateInterval;
@property(nonatomic) unsigned int backgroundFetchInterval; // @dynamic backgroundFetchInterval;
@property(retain, nonatomic) NSString *entranceConfig; // @dynamic entranceConfig;
@property(nonatomic) unsigned int fetchinterval; // @dynamic fetchinterval;
@property(nonatomic) unsigned int forbiddenStatus; // @dynamic forbiddenStatus;
@property(nonatomic) unsigned int height; // @dynamic height;
@property(retain, nonatomic) NSString *likeCountWording; // @dynamic likeCountWording;
@property(retain, nonatomic) NSString *liveid; // @dynamic liveid;
@property(retain, nonatomic) NSString *liveusername; // @dynamic liveusername;
@property(retain, nonatomic) NSString *menuDonationWording; // @dynamic menuDonationWording;
@property(nonatomic) unsigned int musicPlayFlag; // @dynamic musicPlayFlag;
@property(retain, nonatomic) NSString *objectNonceId; // @dynamic objectNonceId;
@property(retain, nonatomic) NSString *objectid; // @dynamic objectid;
@property(retain, nonatomic) NSString *onlineCountWording; // @dynamic onlineCountWording;
@property(nonatomic) unsigned int postDayLimit; // @dynamic postDayLimit;
@property(retain, nonatomic) NSString *seenCountWording; // @dynamic seenCountWording;
@property(nonatomic) unsigned int width; // @dynamic width;

@end

