//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FestivalWishConfig, NSArray, NSString, WDCommonWishInfo;

@protocol IWeDrawManagerExt <NSObject>

@optional
- (void)onMusicPlayFlagChange:(unsigned int)arg1;
- (void)onForbiddenStatusChange:(unsigned int)arg1;
- (void)onWDHomeVCDealloc;
- (void)onSeenDescChange:(NSString *)arg1;
- (void)onOnLineDescChange:(NSString *)arg1;
- (void)onLikeDescChange:(NSString *)arg1;
- (void)onLiveNeedToStopNow;
- (void)onNewMessage:(NSArray *)arg1;
- (void)onMusicListChange:(NSArray *)arg1;
- (void)onCurrentWishDetail:(WDCommonWishInfo *)arg1;
- (void)moveToFootprint:(WDCommonWishInfo *)arg1;
- (void)onCanvasDataChange:(NSString *)arg1 md5:(NSString *)arg2 interval:(unsigned int)arg3 width:(unsigned int)arg4 height:(unsigned int)arg5;
- (void)onPostMyWish:(WDCommonWishInfo *)arg1;
- (void)onFriendWishesChange:(NSArray *)arg1;
- (void)onWishConfigLiveChange:(FestivalWishConfig *)arg1;
- (void)onFestivalInitError:(int)arg1;
- (void)onFestivalWishInit:(FestivalWishConfig *)arg1;
@end

