//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WALiteBackOffDelegate-Protocol.h"

@class MEPackageChecker, NSString, UITableView, UIView, WALiteJITRuntime;
@protocol MEFrameworkLoadDelegate;

@interface MEFramework : NSObject <WALiteBackOffDelegate>
{
    UITableView *m_TableView;
    _Bool isLoad;
    _Bool _pkgReady;
    _Bool _wkReady;
    _Bool _gameReady;
    _Bool _hasInitExpr;
    _Bool _isDebugMode;
    _Bool _shouldUseVConsole;
    int _debugType;
    unsigned int _devUin;
    MEPackageChecker *_pkgChecker;
    WALiteJITRuntime *_jitRuntime;
    id <MEFrameworkLoadDelegate> _loadDelegate;
    UIView *_msgContentView;
    NSString *_debugAppID;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool shouldUseVConsole; // @synthesize shouldUseVConsole=_shouldUseVConsole;
@property(retain, nonatomic) NSString *debugAppID; // @synthesize debugAppID=_debugAppID;
@property(nonatomic) unsigned int devUin; // @synthesize devUin=_devUin;
@property(nonatomic) int debugType; // @synthesize debugType=_debugType;
@property(nonatomic) _Bool isDebugMode; // @synthesize isDebugMode=_isDebugMode;
@property(nonatomic) _Bool hasInitExpr; // @synthesize hasInitExpr=_hasInitExpr;
@property(nonatomic) __weak UIView *msgContentView; // @synthesize msgContentView=_msgContentView;
@property(nonatomic) _Bool gameReady; // @synthesize gameReady=_gameReady;
@property(nonatomic) _Bool wkReady; // @synthesize wkReady=_wkReady;
@property(nonatomic) _Bool pkgReady; // @synthesize pkgReady=_pkgReady;
@property(nonatomic) __weak id <MEFrameworkLoadDelegate> loadDelegate; // @synthesize loadDelegate=_loadDelegate;
@property(retain, nonatomic) WALiteJITRuntime *jitRuntime; // @synthesize jitRuntime=_jitRuntime;
@property(retain, nonatomic) MEPackageChecker *pkgChecker; // @synthesize pkgChecker=_pkgChecker;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)onWKTerminate;
- (void)loadGame;
- (void)onWebViewReady;
- (void)onInject:(_Bool)arg1;
- (_Bool)hasLoaded;
- (id)getVisibleMsgMetaDict:(_Bool)arg1;
- (id)getMsgMetaFromMsgId:(unsigned int)arg1 needFrame:(_Bool)arg2;
- (void)clearVFX;
- (id)getWK;
- (void)sendMagicEmoji:(id)arg1 msgId:(unsigned int)arg2 reportInfo:(id)arg3;
- (_Bool)isInDarkMode;
- (void)onDarkModeChanged:(_Bool)arg1;
- (void)dealloc;
- (void)initForRelease:(struct CGRect)arg1;
- (void)initForDebug:(struct CGRect)arg1;
- (void)initExpr;
- (id)initWithFrame:(struct CGRect)arg1 loadDelegate:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

