//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMRootService.h"

#import "IExptServiceExt-Protocol.h"
#import "MMKernelExt-Protocol.h"
#import "MMServiceProtocol-Protocol.h"
#import "WCMemoryStatPluginDelegate-Protocol.h"

@class MemoryRecordInfo, MemoryStatConfig, MemoryStatReporter, NSString, WCMemoryStatPlugin;

@interface MemoryStatManager : MMRootService <MMKernelExt, IExptServiceExt, WCMemoryStatPluginDelegate, MMServiceProtocol>
{
    NSString *m_rootDir;
    NSString *m_dataDir;
    NSString *m_configPath;
    MemoryStatConfig *m_config;
    MemoryRecordInfo *m_lastRecord;
    MemoryRecordInfo *m_currRecord;
    unsigned long long m_userType;
    WCMemoryStatPlugin *m_plugin;
    MemoryStatReporter *m_reporter;
    _Bool m_currentOpenMemStat;
}

- (void).cxx_destruct;
- (id)onMemoryStatPluginGetCustomInfo:(id)arg1;
- (void)onMemoryStatPlugin:(id)arg1 hasError:(int)arg2;
- (id)currUsrName;
- (void)setupStrategyFromXLab;
- (void)onExptItemListChange;
- (void)onAuthOK;
- (void)doIDKeyReport:(int)arg1 value:(int)arg2;
- (void)getlastFOOMThreadInfos;
- (void)handleAppFirstBecomeActive:(id)arg1;
- (void)handleDidBecomeActiveNotification:(id)arg1;
- (void)saveConfig;
- (void)loadConfig;
- (void)onSignalCrash;
- (void)dumpMemoryAndSummaryReport:(id)arg1;
- (unsigned int)getCurrentThreadMemoryUsage;
- (void)removeCurrentThread;
- (void)addCurrentThreadToMonitor:(id)arg1;
- (void)uploadReport:(id)arg1;
- (id)recordList;
- (void)uploadLastReport;
- (_Bool)shouldEnterUploadReport;
- (void)setMemoryStatEnabled:(_Bool)arg1;
- (_Bool)isMemoryStatEnabled;
- (void)startTracking;
- (_Bool)checkDeviceSatisfied;
- (void)checkAndRecord;
- (void)onServiceInit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

