//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "MMFinderLiveConnectMicVideoOperationViewDelegate-Protocol.h"

@class MMFinderLiveConnectMicVideoOperationView, MMFinderLiveTaskId, NSArray, NSMutableDictionary, NSString;
@protocol MMFinderLiveConnectMicAllUserInfoViewDelegate, MMFinderLiveConnectMicAllUserInfoViewGiftNotificationDelegate;

@interface MMFinderLiveConnectMicAllUserInfoView : UIView <MMFinderLiveConnectMicVideoOperationViewDelegate>
{
    _Bool _needHidden;
    id <MMFinderLiveConnectMicAllUserInfoViewDelegate> _actionDelegate;
    id <MMFinderLiveConnectMicAllUserInfoViewGiftNotificationDelegate> _giftNotificationDelegate;
    MMFinderLiveTaskId *_finderLiveTaskId;
    MMFinderLiveConnectMicVideoOperationView *_currentAnchorInfoView;
    NSArray *_userInfoList;
    NSMutableDictionary *_userViewWrapDic;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableDictionary *userViewWrapDic; // @synthesize userViewWrapDic=_userViewWrapDic;
@property(retain, nonatomic) NSArray *userInfoList; // @synthesize userInfoList=_userInfoList;
@property(retain, nonatomic) MMFinderLiveConnectMicVideoOperationView *currentAnchorInfoView; // @synthesize currentAnchorInfoView=_currentAnchorInfoView;
@property(retain, nonatomic) MMFinderLiveTaskId *finderLiveTaskId; // @synthesize finderLiveTaskId=_finderLiveTaskId;
@property(nonatomic) _Bool needHidden; // @synthesize needHidden=_needHidden;
@property(nonatomic) __weak id <MMFinderLiveConnectMicAllUserInfoViewGiftNotificationDelegate> giftNotificationDelegate; // @synthesize giftNotificationDelegate=_giftNotificationDelegate;
@property(nonatomic) __weak id <MMFinderLiveConnectMicAllUserInfoViewDelegate> actionDelegate; // @synthesize actionDelegate=_actionDelegate;
- (void)onMMFinderLiveConnectMicVideoOperationViewTapSendRedPacketWithUserInfo:(id)arg1;
- (void)onMMFinderLiveConnectMicVideoOperationViewTapAvatarWithUserInfo:(id)arg1;
- (void)onMMFinderLiveConnectMicVideoOperationViewSwitchCameraWithUserInfo:(id)arg1;
- (void)onMMFinderLiveConnectMicVideoOperationViewTapHangupWithUserInfo:(id)arg1;
- (double)getHeightByWidth:(double)arg1;
- (void)clearAndHide;
- (void)showWithConnectMicUserInfoList:(id)arg1;
- (void)layoutUI;
- (void)configCurrentAnchorInfoView;
- (id)generateGiftNotificationContainerViewsDic;
- (void)updateConnectMicUserViews;
- (void)clearUserViewWrapDicAndConnectMicUserViews;
- (void)layoutSubviews;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)initWithTaskId:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 andTaskId:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

