//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MMFinderLiveConnectMicUser;

@protocol MMFinderLiveConnectMicVideoOperationViewDelegate <NSObject>

@optional
- (void)onMMFinderLiveConnectMicVideoOperationViewTapSendRedPacketWithUserInfo:(MMFinderLiveConnectMicUser *)arg1;
- (void)onMMFinderLiveConnectMicVideoOperationViewTapAvatarWithUserInfo:(MMFinderLiveConnectMicUser *)arg1;
- (void)onMMFinderLiveConnectMicVideoOperationViewSwitchCameraWithUserInfo:(MMFinderLiveConnectMicUser *)arg1;
- (void)onMMFinderLiveConnectMicVideoOperationViewTapHangupWithUserInfo:(MMFinderLiveConnectMicUser *)arg1;
@end

