//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSString;

@interface MMFinderLiveGameUserInfo : NSObject <NSCopying>
{
    unsigned int _appStatus;
    unsigned int _playingStatus;
    unsigned int _liveStatus;
    NSString *_appId;
    NSString *_appName;
    NSString *_iconUrl;
    NSString *_downloadUrl;
    NSString *_defaultLiveCoverUrl;
    NSString *_liveCoverUrl;
    NSString *_liveDescription;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *liveDescription; // @synthesize liveDescription=_liveDescription;
@property(retain, nonatomic) NSString *liveCoverUrl; // @synthesize liveCoverUrl=_liveCoverUrl;
@property(nonatomic) unsigned int liveStatus; // @synthesize liveStatus=_liveStatus;
@property(nonatomic) unsigned int playingStatus; // @synthesize playingStatus=_playingStatus;
@property(retain, nonatomic) NSString *defaultLiveCoverUrl; // @synthesize defaultLiveCoverUrl=_defaultLiveCoverUrl;
@property(nonatomic) unsigned int appStatus; // @synthesize appStatus=_appStatus;
@property(retain, nonatomic) NSString *downloadUrl; // @synthesize downloadUrl=_downloadUrl;
@property(retain, nonatomic) NSString *iconUrl; // @synthesize iconUrl=_iconUrl;
@property(retain, nonatomic) NSString *appName; // @synthesize appName=_appName;
@property(retain, nonatomic) NSString *appId; // @synthesize appId=_appId;
- (void)copyFromPBItem:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithPBItem:(id)arg1;

@end

