//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMLiveOperationViewDelegate-Protocol.h"

@class FinderLiveShopWindowAdItem, FinderLiveShopWindowProductItem, MMFinderLiveAdsItem, MMFinderLiveGoodsItem;

@protocol MMFinderLiveOperationViewDelegate <MMLiveOperationViewDelegate>

@optional
- (void)onMMLiveOperationSendRedPacket;
- (void)onMMLiveOperationFindMoreLive;
- (void)checkAndCloseHalfScreenView;
- (void)onMMLiveOperationCreateLotteryBtnClicked;
- (void)onMMLiveOperationLiveGoodsTipViewClickedForAudienceWithAdItem:(FinderLiveShopWindowAdItem *)arg1;
- (void)onMMLiveOperationLiveGoodsTipViewClickedForAudience:(FinderLiveShopWindowProductItem *)arg1;
- (void)onMMLiveOperationOpenRewardInstructionPage;
- (void)onMMLiveOperationLiveAdsButtonClicked:(MMFinderLiveAdsItem *)arg1;
- (void)onMMLiveOperationLiveShoppingButtonClicked:(MMFinderLiveGoodsItem *)arg1;
@end

