//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ILocationMgrExt-Protocol.h"

@class FinderLocation, MMLiveTaskId, NSString, WCFinderDataItem, WCFinderLiveShareItem;

@interface MMFinderGameLiveStarterViewModel : NSObject <ILocationMgrExt>
{
    int _createGameLiveScene;
    WCFinderDataItem *_dataItem;
    WCFinderLiveShareItem *_shareItem;
    long long _entryScene;
    NSString *_appId;
    FinderLocation *_locationInfo;
    NSString *_liveGameAuthTicket;
    NSString *_liveCoverUrl;
    NSString *_defaultLiveCoverUrl;
    NSString *_liveDescription;
    MMLiveTaskId *_liveTaskId;
}

- (void).cxx_destruct;
@property(retain, nonatomic) MMLiveTaskId *liveTaskId; // @synthesize liveTaskId=_liveTaskId;
@property(retain, nonatomic) NSString *liveDescription; // @synthesize liveDescription=_liveDescription;
@property(retain, nonatomic) NSString *defaultLiveCoverUrl; // @synthesize defaultLiveCoverUrl=_defaultLiveCoverUrl;
@property(retain, nonatomic) NSString *liveCoverUrl; // @synthesize liveCoverUrl=_liveCoverUrl;
@property(retain, nonatomic) NSString *liveGameAuthTicket; // @synthesize liveGameAuthTicket=_liveGameAuthTicket;
@property(retain, nonatomic) FinderLocation *locationInfo; // @synthesize locationInfo=_locationInfo;
@property(retain, nonatomic) NSString *appId; // @synthesize appId=_appId;
@property(nonatomic) int createGameLiveScene; // @synthesize createGameLiveScene=_createGameLiveScene;
@property(nonatomic) long long entryScene; // @synthesize entryScene=_entryScene;
@property(retain, nonatomic) WCFinderLiveShareItem *shareItem; // @synthesize shareItem=_shareItem;
@property(retain, nonatomic) WCFinderDataItem *dataItem; // @synthesize dataItem=_dataItem;
- (void)createGameLivePrepareSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (void)updateLocationInfoWithCachedLocation:(id)arg1;
- (id)getLiveDescription;
- (void)updateLiveGameAuthTicket:(id)arg1;
- (void)updateLiveDescription:(id)arg1;
- (void)updateLiveShareItem:(id)arg1;
- (void)updateGameLiveDataItem;
- (id)getLiveCoverUrl;
- (void)updateLiveCoverUrl:(id)arg1;
- (id)initWithLiveTaskId:(id)arg1 appId:(id)arg2 andGameLiveEntryScene:(long long)arg3;

@end

