//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class MMFinderLiveConnectMicUser, MMFinderLiveTaskId, UILabel, WCFinderHeadImageView;
@protocol WCFinderHeadImageViewDelegate;

@interface MMFinderLiveConnectMicBaseUserInfoView : UIView
{
    MMFinderLiveTaskId *_finderLiveTaskId;
    MMFinderLiveConnectMicUser *_connectMicUserInfo;
    WCFinderHeadImageView *_headImageView;
    UILabel *_nicknameLabel;
    UILabel *_connectMicTipLabel;
    id <WCFinderHeadImageViewDelegate> _headImageViewDelegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <WCFinderHeadImageViewDelegate> headImageViewDelegate; // @synthesize headImageViewDelegate=_headImageViewDelegate;
@property(retain, nonatomic) UILabel *connectMicTipLabel; // @synthesize connectMicTipLabel=_connectMicTipLabel;
@property(retain, nonatomic) UILabel *nicknameLabel; // @synthesize nicknameLabel=_nicknameLabel;
@property(retain, nonatomic) WCFinderHeadImageView *headImageView; // @synthesize headImageView=_headImageView;
@property(retain, nonatomic) MMFinderLiveConnectMicUser *connectMicUserInfo; // @synthesize connectMicUserInfo=_connectMicUserInfo;
@property(retain, nonatomic) MMFinderLiveTaskId *finderLiveTaskId; // @synthesize finderLiveTaskId=_finderLiveTaskId;
- (void)configConnectMicTipLabel;
- (void)configNicknameLabel;
- (void)configHeadImageView;
- (void)updateHeadImageViewSize;

@end

