//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMFinderLiveConnectMicBaseUserInfoView.h"

@class UIImageView;

@interface MMFinderLiveConnectMicAudioUserInfoView : MMFinderLiveConnectMicBaseUserInfoView
{
    UIImageView *_talkingIconView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIImageView *talkingIconView; // @synthesize talkingIconView=_talkingIconView;
- (void)layoutUIAndSizeToFitWithMaxWidth:(double)arg1 looseLayout:(_Bool)arg2;
- (void)configTalkingIconView;
- (void)updateHeadImageViewSize;

@end

