//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "MMWebImageViewDelegate-Protocol.h"
#import "WCLiveVideoViewDelegate-Protocol.h"

@class MMLiveTaskId, MMUIButton, MMUIImageView, MMUILabel, NSArray, NSMutableDictionary, NSString, WCLiveVideoView;
@protocol MMLiveViewDelegate;

@interface MMLiveView : UIView <WCLiveVideoViewDelegate, MMWebImageViewDelegate>
{
    _Bool _isInCdnUserConnectedRoomUI;
    _Bool _liveDidStart;
    _Bool _isShowingTips;
    _Bool _isShowingLoading;
    _Bool _shouldHideSmallLocalVideoViewWhenMaximize;
    _Bool _shouldHideSmallRemoteVideoViewWhenMaximize;
    _Bool _isInMinimizeMode;
    id <MMLiveViewDelegate> _delegate;
    WCLiveVideoView *_localVideoView;
    WCLiveVideoView *_bigVideoView;
    WCLiveVideoView *_smallLocalVideoView;
    WCLiveVideoView *_smallRemoteVideoView;
    WCLiveVideoView *_otherConnectMicUserVideoView;
    UIView *_cdnPlayerView;
    MMUIButton *_smallVideoSwitchCameraButton;
    MMLiveTaskId *_taskId;
    NSString *_smallRemoteVideoViewUserId;
    NSArray *_micUserInfoList;
    UIView *_blurBackgroundView;
    UIView *_landScapeBackGroundView;
    MMUILabel *_fullViewTipsLabel;
    MMUIImageView *_fullViewLoadingView;
    MMUILabel *_fullViewLoadingLabel;
    UIView *_videoContainerView;
    NSString *_otherConnectMicUserVideoViewUserId;
    NSMutableDictionary *_micUserViewInfoDic;
    struct CGSize _cdnUserConnectedRoomVideoViewSize;
    struct CGRect _currentMainVideoViewFrame;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableDictionary *micUserViewInfoDic; // @synthesize micUserViewInfoDic=_micUserViewInfoDic;
@property(retain, nonatomic) NSString *otherConnectMicUserVideoViewUserId; // @synthesize otherConnectMicUserVideoViewUserId=_otherConnectMicUserVideoViewUserId;
@property(nonatomic) _Bool isInMinimizeMode; // @synthesize isInMinimizeMode=_isInMinimizeMode;
@property(nonatomic) struct CGSize cdnUserConnectedRoomVideoViewSize; // @synthesize cdnUserConnectedRoomVideoViewSize=_cdnUserConnectedRoomVideoViewSize;
@property(nonatomic) _Bool shouldHideSmallRemoteVideoViewWhenMaximize; // @synthesize shouldHideSmallRemoteVideoViewWhenMaximize=_shouldHideSmallRemoteVideoViewWhenMaximize;
@property(nonatomic) _Bool shouldHideSmallLocalVideoViewWhenMaximize; // @synthesize shouldHideSmallLocalVideoViewWhenMaximize=_shouldHideSmallLocalVideoViewWhenMaximize;
@property(retain, nonatomic) UIView *videoContainerView; // @synthesize videoContainerView=_videoContainerView;
@property(retain, nonatomic) MMUILabel *fullViewLoadingLabel; // @synthesize fullViewLoadingLabel=_fullViewLoadingLabel;
@property(retain, nonatomic) MMUIImageView *fullViewLoadingView; // @synthesize fullViewLoadingView=_fullViewLoadingView;
@property(retain, nonatomic) MMUILabel *fullViewTipsLabel; // @synthesize fullViewTipsLabel=_fullViewTipsLabel;
@property(retain, nonatomic) UIView *landScapeBackGroundView; // @synthesize landScapeBackGroundView=_landScapeBackGroundView;
@property(retain, nonatomic) UIView *blurBackgroundView; // @synthesize blurBackgroundView=_blurBackgroundView;
@property(nonatomic) struct CGRect currentMainVideoViewFrame; // @synthesize currentMainVideoViewFrame=_currentMainVideoViewFrame;
@property(retain, nonatomic) NSArray *micUserInfoList; // @synthesize micUserInfoList=_micUserInfoList;
@property(nonatomic) _Bool isShowingLoading; // @synthesize isShowingLoading=_isShowingLoading;
@property(nonatomic) _Bool isShowingTips; // @synthesize isShowingTips=_isShowingTips;
@property(nonatomic) _Bool liveDidStart; // @synthesize liveDidStart=_liveDidStart;
@property(nonatomic) _Bool isInCdnUserConnectedRoomUI; // @synthesize isInCdnUserConnectedRoomUI=_isInCdnUserConnectedRoomUI;
@property(retain, nonatomic) NSString *smallRemoteVideoViewUserId; // @synthesize smallRemoteVideoViewUserId=_smallRemoteVideoViewUserId;
@property(retain, nonatomic) MMLiveTaskId *taskId; // @synthesize taskId=_taskId;
@property(retain, nonatomic) MMUIButton *smallVideoSwitchCameraButton; // @synthesize smallVideoSwitchCameraButton=_smallVideoSwitchCameraButton;
@property(retain, nonatomic) UIView *cdnPlayerView; // @synthesize cdnPlayerView=_cdnPlayerView;
@property(retain, nonatomic) WCLiveVideoView *otherConnectMicUserVideoView; // @synthesize otherConnectMicUserVideoView=_otherConnectMicUserVideoView;
@property(retain, nonatomic) WCLiveVideoView *smallRemoteVideoView; // @synthesize smallRemoteVideoView=_smallRemoteVideoView;
@property(retain, nonatomic) WCLiveVideoView *smallLocalVideoView; // @synthesize smallLocalVideoView=_smallLocalVideoView;
@property(retain, nonatomic) WCLiveVideoView *bigVideoView; // @synthesize bigVideoView=_bigVideoView;
@property(retain, nonatomic) WCLiveVideoView *localVideoView; // @synthesize localVideoView=_localVideoView;
@property(nonatomic) __weak id <MMLiveViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) unsigned long long currentMainVideoDisplayType;
- (void)stopLoadingAnimation;
- (void)startLoadingAnimation;
- (void)onWCLiveVideoViewMoveEnd;
- (double)videoViewTopMarginInConnectedRoomUI;
- (id)createBackgroundBlurViewWithLiveTaskId:(id)arg1;
- (void)updateLiveVideoViewAppearance:(_Bool)arg1;
@property(readonly, nonatomic) _Bool isShowingVideoView;
- (_Bool)changeToNormalStateForCdnUser;
- (_Bool)changeToCdnUserConnectedRoomStateWithVideoSize:(struct CGSize)arg1;
- (void)updateConnectMicViewsWithUserInfoList:(id)arg1;
- (void)clearConnectMicViewsAndDic;
- (struct CGSize)totalSizeForConnectMicViews;
@property(readonly, nonatomic) _Bool isInConnectedMicUI;
- (void)prepareForMaximizeMode;
- (void)prepareForMinimizeMode;
- (void)updateLocalVideoViewForConnectMic:(_Bool)arg1;
- (struct CGRect)getSmallVideoMixRectRatio;
- (void)showFullScreenLoading:(_Bool)arg1 withLoadingText:(id)arg2;
- (void)showFullViewTips:(unsigned long long)arg1;
- (void)switchCamera;
- (void)startLocalVideo;
- (void)onLoadImageOK:(id)arg1;
- (void)layoutConnectMicUsersView;
- (void)smallVideoSwitchCameraAction;
- (struct CGPoint)getAudienceRemoteVideoViewCenterForScene:(unsigned long long)arg1 withDisplaySize:(struct CGSize)arg2;
- (struct CGRect)createRemoteViewFrameWithDisplaySize:(struct CGSize)arg1 scene:(unsigned long long)arg2;
- (void)updateMainVideoViewFrame:(struct CGRect)arg1;
- (struct CGRect)getMainVideoViewFrame;
- (void)layoutCDNView;
- (void)layoutBlurBackgroundView;
- (void)layoutSmallVideoSwitchCameraButton;
- (void)layoutSmallRemoteVideoViewWithUserId:(id)arg1;
- (void)layoutSmallRemoteVideoView;
- (void)layoutSmallLocalVideoView;
- (void)layoutBigVideoView;
- (void)layoutVideoContainerView;
- (void)layoutUI;
- (void)forceLayoutForOrientationChanged;
- (void)layoutSubviews;
- (struct CGRect)smallRemoteVideoViewFrame;
- (struct CGRect)smallLocalVideoViewFrame;
- (struct CGRect)bigVideoViewFrame;
@property(readonly, nonatomic) _Bool isAudience;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 andTaskId:(id)arg2 andDelegate:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

