//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUserService.h"

#import "IMinimizeTaskDelegateInterface-Protocol.h"
#import "IMinimizeTaskExt-Protocol.h"
#import "IMusicPlayerExt-Protocol.h"
#import "MMImageLoaderObserver-Protocol.h"
#import "MMServiceProtocol-Protocol.h"

@class MMMusicInfo, MMMusicViewController, MMUIButton, NSString, UIView;

@interface MMMusicMVMinimizationMgr : MMUserService <IMusicPlayerExt, IMinimizeTaskDelegateInterface, MMImageLoaderObserver, IMinimizeTaskExt, MMServiceProtocol>
{
    MMMusicViewController *_nativePlayerViewController;
    _Bool _startSuccesss;
    MMMusicInfo *_lastPlayMusic;
    UIView *_minimizeContainerView;
    MMUIButton *_minimizeCoverBgBtn;
    MMUIButton *_minimizeCloseBtn;
}

- (void).cxx_destruct;
@property(retain, nonatomic) MMUIButton *minimizeCloseBtn; // @synthesize minimizeCloseBtn=_minimizeCloseBtn;
@property(retain, nonatomic) MMUIButton *minimizeCoverBgBtn; // @synthesize minimizeCoverBgBtn=_minimizeCoverBgBtn;
@property(retain, nonatomic) UIView *minimizeContainerView; // @synthesize minimizeContainerView=_minimizeContainerView;
@property(nonatomic) _Bool startSuccesss; // @synthesize startSuccesss=_startSuccesss;
@property(retain, nonatomic) MMMusicInfo *lastPlayMusic; // @synthesize lastPlayMusic=_lastPlayMusic;
- (void)onAppTaskDidEnterBackground:(id)arg1 mode:(long long)arg2;
- (void)ImageDidLoadWithData:(id)arg1 Url:(id)arg2;
- (void)onEnterRecentUsedTask:(id)arg1;
- (id)decodeMusicInfoWithTaskData:(id)arg1;
- (id)encodeMusicInfo:(id)arg1;
- (id)genMinimizationMusicPlayerTaskKey;
- (id)dataFromMusicInfo:(id)arg1;
- (void)updateMinimizeContainerViewStickyOrientation:(_Bool)arg1;
- (void)onAbsorbFloatingViewEndResultMoveTo:(struct CGPoint)arg1;
- (_Bool)onTaskStateChanged:(id)arg1 NeedStopState:(_Bool)arg2;
- (id)getLastViewControllerOnLeaveTaskBeforeEnterAnother:(id)arg1;
- (void)onEnterMinimizedTask:(id)arg1 openContext:(id)arg2 taskEnterScene:(unsigned int)arg3;
- (id)transitionController;
- (void)addMusicPlayerToMinimizationList:(id)arg1;
- (void)doMinimizeOnDismiss:(id)arg1;
- (_Bool)removeMinimizeTask;
- (id)getCurMusicMinimizeTask;
- (_Bool)isMusicPlayerAddedToMinimizationList;
- (void)delayHiddenMusicMinimizationViewIfPlayerIdle:(id)arg1;
- (void)prepareForMusicPlay:(id)arg1;
- (void)onMusicPlayInnerStatusChanged:(unsigned long long)arg1 musicInfo:(id)arg2 errInfo:(id)arg3;
- (id)createUsedTaskDataWithMusicInfo:(id)arg1;
- (void)onMinimizeMusicCloseClicked;
- (void)onMinimizeMusicContainerClicked;
- (void)installMinimizeContainerView;
- (void)updateCurMusicViewController:(id)arg1;
- (void)updateCurThumbViewWithMusicInfo:(id)arg1;
- (void)updateMinimizeContainerViewWithThumbImage:(id)arg1;
- (void)updateCurThumbImage:(id)arg1 musicId:(id)arg2;
- (id)getCurPlayerViewController;
- (void)commonInit;
- (void)onServiceTerminate;
- (void)onServiceInit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

