//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class BaseResponse, FestivalWish, NSString;

@interface PostFestivalWishResp : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *afterDonateDesc; // @dynamic afterDonateDesc;
@property(retain, nonatomic) NSString *afterDonateLinkText; // @dynamic afterDonateLinkText;
@property(retain, nonatomic) NSString *afterDonateTitle; // @dynamic afterDonateTitle;
@property(retain, nonatomic) NSString *afterDonateUrl; // @dynamic afterDonateUrl;
@property(retain, nonatomic) BaseResponse *baseResponse; // @dynamic baseResponse;
@property(nonatomic) _Bool hitDonation; // @dynamic hitDonation;
@property(nonatomic) unsigned int postinterval; // @dynamic postinterval;
@property(retain, nonatomic) NSString *textStatusSourceactivityid; // @dynamic textStatusSourceactivityid;
@property(retain, nonatomic) NSString *textStatusSourcename; // @dynamic textStatusSourcename;
@property(retain, nonatomic) NSString *textStatusVerifyInfoBuf; // @dynamic textStatusVerifyInfoBuf;
@property(retain, nonatomic) FestivalWish *wish; // @dynamic wish;

@end

