//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseMsgContentViewController.h"

@class MMHeadImageView, MMUILabel, NSString, UIButton, UIView;

@interface TemplateMsgSubViewController : BaseMsgContentViewController
{
    NSString *_templateSessionId;
    UIView *_headerBarView;
    UIView *_headerLineView;
    UIButton *_headerBarButton;
    MMHeadImageView *_headView;
    MMUILabel *_nickNameLabel;
    MMUILabel *_typeLabel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) MMUILabel *typeLabel; // @synthesize typeLabel=_typeLabel;
@property(retain, nonatomic) MMUILabel *nickNameLabel; // @synthesize nickNameLabel=_nickNameLabel;
@property(retain, nonatomic) MMHeadImageView *headView; // @synthesize headView=_headView;
@property(retain, nonatomic) UIButton *headerBarButton; // @synthesize headerBarButton=_headerBarButton;
@property(retain, nonatomic) UIView *headerLineView; // @synthesize headerLineView=_headerLineView;
@property(retain, nonatomic) UIView *headerBarView; // @synthesize headerBarView=_headerBarView;
@property(retain, nonatomic) NSString *templateSessionId; // @synthesize templateSessionId=_templateSessionId;
- (void)onSettingButton:(id)arg1;
- (void)didReceiveMemoryWarning;
- (double)getTipsHeight;
- (void)viewDidLayoutSubviews;
- (void)onClickHeaderBar:(id)arg1;
- (void)initHeaderBar;
- (void)viewDidLoad;
- (void)dealloc;

@end

