//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "PBCoding-Protocol.h"

@class NSString;

@interface TextStateResidentIconWrap : NSObject <PBCoding>
{
    NSString *iconId;
    NSString *residentCategoryId;
}

+ (id)residentIconWrapWithId:(id)arg1 categoryId:(id)arg2;
+ (void)initialize;
+ (void)PBArrayAdd_residentCategoryId;
+ (void)PBArrayAdd_iconId;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *residentCategoryId; // @synthesize residentCategoryId;
@property(retain, nonatomic) NSString *iconId; // @synthesize iconId;
- (id)getPBPropertyTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

