//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "BaseEmoticonViewDelegate-Protocol.h"
#import "EmoticonBoardViewDelegate-Protocol.h"
#import "IMMTextStateCameraMgrExt-Protocol.h"
#import "MMGrowTextViewDelegate-Protocol.h"
#import "TextStateMgrExt-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"
#import "WCGroupTagViewControllerDelegate-Protocol.h"
#import "WCTimelinePOIPickerViewControllerDelegate-Protocol.h"

@class CAGradientLayer, CEmoticonWrap, EmoticonBoardView, MMEmoticonView, MMGrowTextView, MMTextStateMediaItem, MMTextStateVideoItem, MMUIButton, MMUILabel, NSArray, NSString, TextStateIconWrap, TextStateModel, TextStatePublishCustomCardView, TextStatePublishGuideView, TextStatePublishIconButton, TextStatePublishIconCollectionView, TextStatePublishMediaView, TextStatePublishReportObject, TextStatePublishSourceInfo, TextStatePublishSourceView, UIBarButtonItem, UIButton, UIScreenEdgePanGestureRecognizer, UITapGestureRecognizer, UIView, UIViewPropertyAnimator, WCLocationInfo;
@protocol TextStatePublishViewControllerDelegate;

@interface TextStatePublishViewController : MMUIViewController <WCTimelinePOIPickerViewControllerDelegate, WCGroupTagViewControllerDelegate, EmoticonBoardViewDelegate, BaseEmoticonViewDelegate, IMMTextStateCameraMgrExt, MMGrowTextViewDelegate, UIGestureRecognizerDelegate, TextStateMgrExt>
{
    _Bool _strictInputEmoji;
    _Bool _isBeingLayouted;
    _Bool _showingExceedMaxLengthToast;
    unsigned int _enterScene;
    id <TextStatePublishViewControllerDelegate> _delegate;
    TextStatePublishSourceInfo *_sourceInfo;
    NSString *_sessionId;
    UIBarButtonItem *_exitBarButton;
    TextStatePublishMediaView *_backgroundImageView;
    CAGradientLayer *_backgroundGradientLayer;
    TextStatePublishMediaView *_backgroundCardMediaView;
    MMUIButton *_blurButton;
    UIView *_headerView;
    TextStatePublishIconButton *_headerIconButton;
    TextStatePublishSourceView *_sourceView;
    UIView *_contentView;
    MMGrowTextView *_descriptionTextView;
    MMUIButton *_topicTextButton;
    MMUILabel *_positionLabel;
    UIView *_bottomToolBar;
    NSArray *_bottomToolButtonList;
    UIButton *_emoticonButton;
    UIButton *_privacyButton;
    MMUIButton *_bottomDoneButton;
    TextStatePublishGuideView *_guideView;
    TextStatePublishIconCollectionView *_iconCollectionView;
    UIViewPropertyAnimator *_iconCollectionViewAnimator;
    CDUnknownBlockType _iconCollectionViewAnimatorCompletionHandler;
    TextStatePublishCustomCardView *_customCardView;
    NSString *_customIconDescription;
    TextStateIconWrap *_iconWrap;
    NSString *_defaultImageId;
    MMTextStateVideoItem *_videoItem;
    MMTextStateMediaItem *_imageItem;
    WCLocationInfo *_positionInfo;
    long long _privacy;
    NSArray *_privacyContactBlackList;
    NSArray *_privacyLabelList;
    NSArray *_privacyContactList;
    EmoticonBoardView *_emoticonBoardView;
    MMEmoticonView *_emoticonView;
    MMUIButton *_emoticonDeleteButton;
    CEmoticonWrap *_emoticonWrap;
    double _keyboardHeight;
    UITapGestureRecognizer *_tapGesture;
    UIScreenEdgePanGestureRecognizer *_screenEdgePanGesture;
    TextStateModel *_textStateModel;
    TextStatePublishReportObject *_reportObject;
}

- (void).cxx_destruct;
@property(retain, nonatomic) TextStatePublishReportObject *reportObject; // @synthesize reportObject=_reportObject;
@property(retain, nonatomic) TextStateModel *textStateModel; // @synthesize textStateModel=_textStateModel;
@property(nonatomic) _Bool showingExceedMaxLengthToast; // @synthesize showingExceedMaxLengthToast=_showingExceedMaxLengthToast;
@property(retain, nonatomic) UIScreenEdgePanGestureRecognizer *screenEdgePanGesture; // @synthesize screenEdgePanGesture=_screenEdgePanGesture;
@property(retain, nonatomic) UITapGestureRecognizer *tapGesture; // @synthesize tapGesture=_tapGesture;
@property(nonatomic) double keyboardHeight; // @synthesize keyboardHeight=_keyboardHeight;
@property(nonatomic) _Bool isBeingLayouted; // @synthesize isBeingLayouted=_isBeingLayouted;
@property(retain, nonatomic) CEmoticonWrap *emoticonWrap; // @synthesize emoticonWrap=_emoticonWrap;
@property(retain, nonatomic) MMUIButton *emoticonDeleteButton; // @synthesize emoticonDeleteButton=_emoticonDeleteButton;
@property(retain, nonatomic) MMEmoticonView *emoticonView; // @synthesize emoticonView=_emoticonView;
@property(retain, nonatomic) EmoticonBoardView *emoticonBoardView; // @synthesize emoticonBoardView=_emoticonBoardView;
@property(retain, nonatomic) NSArray *privacyContactList; // @synthesize privacyContactList=_privacyContactList;
@property(retain, nonatomic) NSArray *privacyLabelList; // @synthesize privacyLabelList=_privacyLabelList;
@property(retain, nonatomic) NSArray *privacyContactBlackList; // @synthesize privacyContactBlackList=_privacyContactBlackList;
@property(nonatomic) long long privacy; // @synthesize privacy=_privacy;
@property(retain, nonatomic) WCLocationInfo *positionInfo; // @synthesize positionInfo=_positionInfo;
@property(retain, nonatomic) MMTextStateMediaItem *imageItem; // @synthesize imageItem=_imageItem;
@property(retain, nonatomic) MMTextStateVideoItem *videoItem; // @synthesize videoItem=_videoItem;
@property(retain, nonatomic) NSString *defaultImageId; // @synthesize defaultImageId=_defaultImageId;
@property(retain, nonatomic) TextStateIconWrap *iconWrap; // @synthesize iconWrap=_iconWrap;
@property(retain, nonatomic) NSString *customIconDescription; // @synthesize customIconDescription=_customIconDescription;
@property(retain, nonatomic) TextStatePublishCustomCardView *customCardView; // @synthesize customCardView=_customCardView;
@property(copy, nonatomic) CDUnknownBlockType iconCollectionViewAnimatorCompletionHandler; // @synthesize iconCollectionViewAnimatorCompletionHandler=_iconCollectionViewAnimatorCompletionHandler;
@property(retain, nonatomic) UIViewPropertyAnimator *iconCollectionViewAnimator; // @synthesize iconCollectionViewAnimator=_iconCollectionViewAnimator;
@property(retain, nonatomic) TextStatePublishIconCollectionView *iconCollectionView; // @synthesize iconCollectionView=_iconCollectionView;
@property(retain, nonatomic) TextStatePublishGuideView *guideView; // @synthesize guideView=_guideView;
@property(retain, nonatomic) MMUIButton *bottomDoneButton; // @synthesize bottomDoneButton=_bottomDoneButton;
@property(retain, nonatomic) UIButton *privacyButton; // @synthesize privacyButton=_privacyButton;
@property(retain, nonatomic) UIButton *emoticonButton; // @synthesize emoticonButton=_emoticonButton;
@property(retain, nonatomic) NSArray *bottomToolButtonList; // @synthesize bottomToolButtonList=_bottomToolButtonList;
@property(retain, nonatomic) UIView *bottomToolBar; // @synthesize bottomToolBar=_bottomToolBar;
@property(retain, nonatomic) MMUILabel *positionLabel; // @synthesize positionLabel=_positionLabel;
@property(retain, nonatomic) MMUIButton *topicTextButton; // @synthesize topicTextButton=_topicTextButton;
@property(retain, nonatomic) MMGrowTextView *descriptionTextView; // @synthesize descriptionTextView=_descriptionTextView;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) TextStatePublishSourceView *sourceView; // @synthesize sourceView=_sourceView;
@property(retain, nonatomic) TextStatePublishIconButton *headerIconButton; // @synthesize headerIconButton=_headerIconButton;
@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) MMUIButton *blurButton; // @synthesize blurButton=_blurButton;
@property(retain, nonatomic) TextStatePublishMediaView *backgroundCardMediaView; // @synthesize backgroundCardMediaView=_backgroundCardMediaView;
@property(retain, nonatomic) CAGradientLayer *backgroundGradientLayer; // @synthesize backgroundGradientLayer=_backgroundGradientLayer;
@property(retain, nonatomic) TextStatePublishMediaView *backgroundImageView; // @synthesize backgroundImageView=_backgroundImageView;
@property(retain, nonatomic) UIBarButtonItem *exitBarButton; // @synthesize exitBarButton=_exitBarButton;
@property(retain, nonatomic) NSString *sessionId; // @synthesize sessionId=_sessionId;
@property(nonatomic) unsigned int enterScene; // @synthesize enterScene=_enterScene;
@property(retain, nonatomic) TextStatePublishSourceInfo *sourceInfo; // @synthesize sourceInfo=_sourceInfo;
@property(nonatomic) _Bool strictInputEmoji; // @synthesize strictInputEmoji=_strictInputEmoji;
@property(nonatomic) __weak id <TextStatePublishViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (_Bool)gestureRecognizer:(id)arg1 shouldBeRequiredToFailByGestureRecognizer:(id)arg2;
- (void)TextDidChanged:(id)arg1 selectedRange:(struct _NSRange)arg2;
- (void)TextViewExceedMaxLength:(id)arg1;
- (void)TextViewDidEnter:(id)arg1;
- (void)TextViewHeightDidChanged:(id)arg1;
- (void)deleteEmoticon;
- (void)didSelectorEmoticon:(id)arg1;
- (void)onSendButtonClicked;
- (void)onTextStateSightPictureTaken:(id)arg1 imageData:(id)arg2 withFrontCamera:(_Bool)arg3 editImageAttr:(id)arg4;
- (void)onTextStateShortVideoTaken:(id)arg1 thumbImg:(id)arg2 editVideoAttr:(id)arg3 paramModel:(id)arg4;
- (void)onPOIReportStr4CommitChanged:(id)arg1;
- (void)onPOIPickerFinished:(id)arg1;
- (void)privacySettingChanged:(long long)arg1 label:(id)arg2 contacts:(id)arg3;
- (void)endEditing;
- (_Bool)isEmoticonBoardViewShowing;
- (_Bool)isGuideViewShowing;
- (_Bool)isCustomCardViewShowing;
- (_Bool)isIconCollectionViewShowing;
- (id)positionNameFromLocationInfo:(id)arg1;
- (void)handleScreenEdgePanGesture:(id)arg1;
- (void)onTapView:(id)arg1;
- (void)onTapEmoticonDeleteButton;
- (void)onTapPrivacyButton:(id)arg1;
- (void)jumpToPositionPickerController;
- (void)onTapPositionButton:(id)arg1;
- (void)onTapEmoticonButton:(id)arg1;
- (void)jumpToImagePickerController;
- (void)onTapBlurButton;
- (void)onTapTakeSightButton:(id)arg1;
- (void)onTapTopicIconButton;
- (void)onTapTopicTextButton;
- (void)onTapExitBarButtonItem;
- (void)onTapDoneButton;
- (void)onKeyboardWillHide:(id)arg1;
- (void)onKeyboardWillChangeFrame:(id)arg1;
- (_Bool)showErrorToastWithText:(id)arg1;
- (void)hideEmoticonBoard;
- (void)showEmoticonBoard;
- (void)hideCustomCardViewWithConfirm;
- (void)hideCustomCardViewWithCancel;
- (void)showCustomCardView:(id)arg1;
- (void)hideIconCollectionViewForFirstEnter;
- (void)hideIconCollectionView;
- (void)showIconCollectionView;
- (double)maxDescriptionTextViewHeight;
- (void)layoutCustomCardView;
- (void)layoutBackgroundView;
- (void)layoutBottomView;
- (void)layoutContentView;
- (void)layoutHeaderView;
- (void)layoutSubviewsAnimated:(_Bool)arg1;
- (void)layoutSubviews;
- (_Bool)useTransparentNavibar;
- (void)checkDone;
- (void)publishTextState;
- (void)clearMediaItem;
- (void)initData;
- (void)initReportObject;
- (void)initGesture;
- (void)initGuideView;
- (void)initCustomCardView;
- (void)initIconCollectionView;
- (id)bottomToolButtonWithTitle:(id)arg1 imageName:(id)arg2;
- (void)initBottomView;
- (void)initContentView;
- (void)initHeaderView;
- (void)initBackgroundView;
- (void)initView;
- (void)initNavigationItem;
- (void)initKeyboardEventListener;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidTransitionToNewSize;
- (void)initRegisterExtension;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

