//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MMUIViewController, WCCgiBlockHelper;

@interface TextStatePermissionLogic : NSObject
{
    MMUIViewController *_fromViewController;
    CDUnknownBlockType _callback;
    long long _xLabConfig;
    WCCgiBlockHelper *_permissionCgi;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WCCgiBlockHelper *permissionCgi; // @synthesize permissionCgi=_permissionCgi;
@property(nonatomic) long long xLabConfig; // @synthesize xLabConfig=_xLabConfig;
@property(copy, nonatomic) CDUnknownBlockType callback; // @synthesize callback=_callback;
@property(nonatomic) __weak MMUIViewController *fromViewController; // @synthesize fromViewController=_fromViewController;
- (unsigned long long)localPermissionType;
- (void)startRequestPermission;
- (void)checkPermissionFromViewController:(id)arg1 callback:(CDUnknownBlockType)arg2;

@end

