//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class KidsWatchTextFieldItem, MMUIButton, TextStateIconWrap, UIImageView, UITextField;

@interface TextStatePublishCustomCardView : UIView
{
    TextStateIconWrap *_customIconWrap;
    CDUnknownBlockType _cancelHandler;
    CDUnknownBlockType _confirmHandler;
    CDUnknownBlockType _exceedMaxLengthHandler;
    UIImageView *_iconImageView;
    KidsWatchTextFieldItem *_textFieldItem;
    UIView *_horizonSeparatorView;
    UIView *_verticalSeparatorView;
    MMUIButton *_cancelButton;
    MMUIButton *_confirmButton;
}

- (void).cxx_destruct;
@property(retain, nonatomic) MMUIButton *confirmButton; // @synthesize confirmButton=_confirmButton;
@property(retain, nonatomic) MMUIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(retain, nonatomic) UIView *verticalSeparatorView; // @synthesize verticalSeparatorView=_verticalSeparatorView;
@property(retain, nonatomic) UIView *horizonSeparatorView; // @synthesize horizonSeparatorView=_horizonSeparatorView;
@property(retain, nonatomic) KidsWatchTextFieldItem *textFieldItem; // @synthesize textFieldItem=_textFieldItem;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(copy, nonatomic) CDUnknownBlockType exceedMaxLengthHandler; // @synthesize exceedMaxLengthHandler=_exceedMaxLengthHandler;
@property(copy, nonatomic) CDUnknownBlockType confirmHandler; // @synthesize confirmHandler=_confirmHandler;
@property(copy, nonatomic) CDUnknownBlockType cancelHandler; // @synthesize cancelHandler=_cancelHandler;
@property(retain, nonatomic) TextStateIconWrap *customIconWrap; // @synthesize customIconWrap=_customIconWrap;
- (void)onTapConfirmButton;
- (void)onTapCancelButton;
- (void)onTapClearButton;
- (void)makeTextFieldFirstResponder;
@property(readonly, nonatomic) UITextField *textField;
- (void)layoutSubviews;
- (void)didMoveToWindow;
- (void)initSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

