//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface TextStateCardReporter : NSObject
{
}

+ (long long)chatroomNumberFor:(id)arg1;
+ (id)extraInfoForAction:(long long)arg1 textStateModel:(id)arg2 username:(id)arg3;
+ (long long)relationShipWithUsername:(id)arg1;
+ (id)currLikeIconForUsername:(id)arg1;
+ (id)sourceExtraInfoForModel:(id)arg1;
+ (id)getSessionIdForScene:(long long)arg1 textStateId:(id)arg2;
+ (void)reportAction:(long long)arg1 scene:(long long)arg2 model:(id)arg3 sessionScene:(unsigned int)arg4 username:(id)arg5 hasNoticeEntry:(_Bool)arg6 positionInList:(long long)arg7;
+ (void)reportAction:(long long)arg1 scene:(long long)arg2 sessionScene:(unsigned int)arg3 contact:(id)arg4 indexInTable:(long long)arg5;
+ (void)reportAction:(long long)arg1 scene:(long long)arg2 sessionScene:(unsigned int)arg3 contact:(id)arg4;
+ (void)reportAction:(long long)arg1 scene:(long long)arg2 contact:(id)arg3;

@end

