//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMWindowViewController.h"

#import "MMMenuWindowDelegate-Protocol.h"

@class CAShapeLayer, MMMenuWindow, NSString, UILabel, UIView;
@protocol TextStateTipsBubbleViewDelegate;

@interface TextStateTipsBubbleView : MMWindowViewController <MMMenuWindowDelegate>
{
    id <TextStateTipsBubbleViewDelegate> _delegate;
    MMMenuWindow *_window;
    UIView *_containerView;
    UILabel *_titleLabel;
    CAShapeLayer *_blurMaskLayer;
}

- (void).cxx_destruct;
@property(retain, nonatomic) CAShapeLayer *blurMaskLayer; // @synthesize blurMaskLayer=_blurMaskLayer;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) MMMenuWindow *window; // @synthesize window=_window;
@property(nonatomic) __weak id <TextStateTipsBubbleViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)onClickAtBackground:(id)arg1;
- (void)onTouchAtNoneMenuArea;
- (void)dismiss;
- (void)showToView:(id)arg1 rect:(struct CGRect)arg2;
- (void)updateBlurMaskWithArrowCenterX:(double)arg1 arrowDirection:(long long)arg2;
- (_Bool)shouldHandleStatusBarAppearance;
- (void)updateWithTitle:(id)arg1;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

