//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAJSEventHandler_BaseEvent.h"

#import "WCFinderCreateCoordinatorDelegate-Protocol.h"
#import "WCFinderPostViewControllerDelegate-Protocol.h"

@class NSString, WCFinderCreateCoordinator;

@interface WAJSEventHandler_openChannelsPostPage : WAJSEventHandler_BaseEvent <WCFinderCreateCoordinatorDelegate, WCFinderPostViewControllerDelegate>
{
    WCFinderCreateCoordinator *_createCoordinator;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WCFinderCreateCoordinator *createCoordinator; // @synthesize createCoordinator=_createCoordinator;
- (void)postViewControllerDidCancel:(id)arg1 dataItem:(id)arg2 postStateModel:(id)arg3;
- (void)postViewControllerDidFinish:(id)arg1 dataItem:(id)arg2 postStateModel:(id)arg3;
- (void)finderCreateCoordinatorStartCreateUserComplete;
- (void)finderRealNameSuccess:(id)arg1;
- (void)finderCreateAccountSuccess:(id)arg1;
- (void)postFinderFromVC:(id)arg1 dataItem:(id)arg2 postStateModel:(id)arg3;
- (void)handleJSEvent:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

