//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAMainFrameTaskBarSectionWeAppView.h"

@interface WAMainFrameTaskBarSectionMyWeAppView : WAMainFrameTaskBarSectionWeAppView
{
    _Bool _isOnTop;
}

@property(nonatomic) _Bool isOnTop; // @synthesize isOnTop=_isOnTop;
- (void)handleClickSearch;
- (void)handleClickMy:(id)arg1;
- (void)handleClickUnStar;
- (void)notifyItemRemoved:(id)arg1;
- (void)notifyItemInserted:(long long)arg1 newItems:(id)arg2;
- (void)showTipsViewController:(id)arg1;
- (_Bool)isInStarList:(id)arg1;
- (void)onLongPress:(id)arg1;
- (void)updateSearchState;
- (void)onClickMore;
- (void)prepareForReuse;
- (void)layoutSubviews;
- (id)title;

@end

