//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WCFinderEventTabInfo : NSObject
{
    long long _innerTabType;
    NSString *_tabName;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *tabName; // @synthesize tabName=_tabName;
@property(nonatomic) long long innerTabType; // @synthesize innerTabType=_innerTabType;

@end

