//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "WCFinderGameLiveListCellDelegate-Protocol.h"
#import "WCFinderGameLiveStarterPrepareViewControllerDelegate-Protocol.h"

@class MMFinderGameLiveStarterViewModel, MMLiveTaskId, MMTableView, NSIndexPath, NSMutableArray, NSString, UIButton, UILabel, UIView;
@protocol WCFinderGameLiveListViewControllerDelegate;

@interface WCFinderGameLiveListViewController : MMUIViewController <UITableViewDelegate, UITableViewDataSource, WCFinderGameLiveListCellDelegate, WCFinderGameLiveStarterPrepareViewControllerDelegate>
{
    id <WCFinderGameLiveListViewControllerDelegate> _delegate;
    MMLiveTaskId *_liveTaskId;
    MMTableView *_tableView;
    UIView *_backgroundView;
    UILabel *_tableTitleLabel;
    UIButton *_confirmButton;
    UIButton *_backButton;
    NSMutableArray *_gameUserInfoList;
    NSString *_appId;
    double _tableHeight;
    NSIndexPath *_lastSelectedIndexPath;
    MMFinderGameLiveStarterViewModel *_gameLiveVM;
}

- (void).cxx_destruct;
@property(retain, nonatomic) MMFinderGameLiveStarterViewModel *gameLiveVM; // @synthesize gameLiveVM=_gameLiveVM;
@property(retain, nonatomic) NSIndexPath *lastSelectedIndexPath; // @synthesize lastSelectedIndexPath=_lastSelectedIndexPath;
@property(nonatomic) double tableHeight; // @synthesize tableHeight=_tableHeight;
@property(retain, nonatomic) NSString *appId; // @synthesize appId=_appId;
@property(retain, nonatomic) NSMutableArray *gameUserInfoList; // @synthesize gameUserInfoList=_gameUserInfoList;
@property(retain, nonatomic) UIButton *backButton; // @synthesize backButton=_backButton;
@property(retain, nonatomic) UIButton *confirmButton; // @synthesize confirmButton=_confirmButton;
@property(retain, nonatomic) UILabel *tableTitleLabel; // @synthesize tableTitleLabel=_tableTitleLabel;
@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) MMTableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) MMLiveTaskId *liveTaskId; // @synthesize liveTaskId=_liveTaskId;
@property(nonatomic) __weak id <WCFinderGameLiveListViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (_Bool)canJumpToGamePrepareLiveView:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)onClickConfirmButton;
- (void)onBackButtonClicked;
- (void)setConfirmButtonEnabel:(_Bool)arg1;
- (void)initBackgroundView;
- (void)layoutUI;
- (void)viewDidLoad;
- (id)initWithTaskId:(id)arg1 gameUserInfoList:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

