//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMTableViewCell.h"

@class MMWebImageView, UILabel, UIView;
@protocol WCFinderGameLiveListCellDelegate;

@interface WCFinderGameLiveListCell : MMTableViewCell
{
    id <WCFinderGameLiveListCellDelegate> _delegate;
    UILabel *_gameName;
    MMWebImageView *_gameIconView;
    UIView *_separator;
    UIView *_checkIconView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIView *checkIconView; // @synthesize checkIconView=_checkIconView;
@property(retain, nonatomic) UIView *separator; // @synthesize separator=_separator;
@property(retain, nonatomic) MMWebImageView *gameIconView; // @synthesize gameIconView=_gameIconView;
@property(retain, nonatomic) UILabel *gameName; // @synthesize gameName=_gameName;
@property(nonatomic) __weak id <WCFinderGameLiveListCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void)unToggle;
- (void)toggle;
- (void)removeSeparator;
- (void)drawSeparator;
- (void)updateWithGameInfo:(id)arg1;
- (void)prepareForReuse;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

