//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WCFinderPostDataItemExt-Protocol.h"
#import "WCFinderTopicDataKeyExt-Protocol.h"

@class FinderEventInfo, FinderTopicBgmInfo, NSData, NSMutableArray, NSString, WCFinderTopicInfo;
@protocol WCFinderEventPageViewModelDelegate;

@interface WCFinderEventPageViewModel : NSObject <WCFinderPostDataItemExt, WCFinderTopicDataKeyExt>
{
    _Bool _continueFlag;
    id <WCFinderEventPageViewModelDelegate> _delegate;
    NSString *_topicTitle;
    unsigned long long _state;
    unsigned long long _commentScene;
    long long _tabType;
    long long _innerTabType;
    long long _fromType;
    unsigned long long _eventTopicId;
    NSString *_encryptedTopicId;
    NSString *_refObjectId;
    NSString *_latestRequestID;
    WCFinderTopicInfo *_topicInfo;
    FinderTopicBgmInfo *_bgmInfo;
    FinderEventInfo *_eventInfo;
    NSData *_lastBuffer;
    NSMutableArray *_contentVMArray;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *contentVMArray; // @synthesize contentVMArray=_contentVMArray;
@property(nonatomic) _Bool continueFlag; // @synthesize continueFlag=_continueFlag;
@property(retain, nonatomic) NSData *lastBuffer; // @synthesize lastBuffer=_lastBuffer;
@property(retain, nonatomic) FinderEventInfo *eventInfo; // @synthesize eventInfo=_eventInfo;
@property(retain, nonatomic) FinderTopicBgmInfo *bgmInfo; // @synthesize bgmInfo=_bgmInfo;
@property(retain, nonatomic) WCFinderTopicInfo *topicInfo; // @synthesize topicInfo=_topicInfo;
@property(copy, nonatomic) NSString *latestRequestID; // @synthesize latestRequestID=_latestRequestID;
@property(copy, nonatomic) NSString *refObjectId; // @synthesize refObjectId=_refObjectId;
@property(copy, nonatomic) NSString *encryptedTopicId; // @synthesize encryptedTopicId=_encryptedTopicId;
@property(nonatomic) unsigned long long eventTopicId; // @synthesize eventTopicId=_eventTopicId;
@property(nonatomic) long long fromType; // @synthesize fromType=_fromType;
@property(nonatomic) long long innerTabType; // @synthesize innerTabType=_innerTabType;
@property(nonatomic) long long tabType; // @synthesize tabType=_tabType;
@property(nonatomic) unsigned long long commentScene; // @synthesize commentScene=_commentScene;
@property(nonatomic) unsigned long long state; // @synthesize state=_state;
@property(copy, nonatomic) NSString *topicTitle; // @synthesize topicTitle=_topicTitle;
@property(nonatomic) __weak id <WCFinderEventPageViewModelDelegate> delegate; // @synthesize delegate=_delegate;
- (void)finderTopicFeedOrderChanged:(unsigned long long)arg1;
- (void)finderFeedOfTopicBeDeleteWithTid:(id)arg1;
- (void)onFinderDataItemPostUpLoadFailWithTid:(id)arg1 errorType:(long long)arg2;
- (void)onFinderDataItemPostUpLoadSuccessful:(id)arg1 localTid:(id)arg2;
- (void)fakeInsertPostEventDataItem:(id)arg1;
- (void)onFinderDataItemStartUpLoad:(id)arg1;
- (void)removeFeedWithTid:(id)arg1;
- (void)updateState;
- (void)requestDataWithPullType:(unsigned long long)arg1;
- (unsigned long long)sortType;
- (id)eventIdStr;
- (id)generateTopicListDetailViewModel;
- (void)requestNextPageData;
- (void)requestFirstPageData;
- (void)dealloc;
- (id)initWithTopicParams:(id)arg1 innerTabType:(long long)arg2 commentScene:(unsigned long long)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

