//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WCTTableCoding-Protocol.h"

@class NSString, WCFinderReportPostStateModel;

@interface WCFinderFeedDraft : NSObject <WCTTableCoding>
{
    _Bool _isNoServerDraft;
    NSString *_draftId;
    long long _objectType;
    WCFinderReportPostStateModel *_postStateModel;
}

+ (void)__wcdb_column_constraint_5:(struct WCTBinding *)arg1;
+ (void)__wcdb_column_constraint_4:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)__wcdb_synthesize_3:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)isNoServerDraft;
+ (const struct WCTProperty *)__wcdb_synthesize_2:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)postStateModel;
+ (const struct WCTProperty *)__wcdb_synthesize_1:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)objectType;
+ (const struct WCTProperty *)__wcdb_synthesize_0:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)draftId;
+ (id)__wcdbtyper;
+ (const SyntaxList_7f15fe8c *)allProperties;
+ (const struct WCTBinding *)objectRelationalMapping;
- (void).cxx_destruct;
@property(nonatomic) _Bool isNoServerDraft; // @synthesize isNoServerDraft=_isNoServerDraft;
@property(retain, nonatomic) WCFinderReportPostStateModel *postStateModel; // @synthesize postStateModel=_postStateModel;
@property(nonatomic) long long objectType; // @synthesize objectType=_objectType;
@property(retain, nonatomic) NSString *draftId; // @synthesize draftId=_draftId;
- (long long)compareWithSorttime:(id)arg1;

// Remaining properties
@property(nonatomic) _Bool isAutoIncrement;
@property(nonatomic) long long lastInsertedRowID;

@end

