//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "WCActionSheetDelegate-Protocol.h"
#import "WCFinderSwitchExt-Protocol.h"

@class NSString, WCFinderLiveAudienceRoleReporter, WCTableViewManager;
@protocol WCFinderTrumpetSelectViewControllerDelegate;

@interface WCFinderTrumpetSelectViewController : MMUIViewController <WCFinderSwitchExt, WCActionSheetDelegate>
{
    id <WCFinderTrumpetSelectViewControllerDelegate> _delegate;
    WCTableViewManager *_tableViewManager;
    WCFinderLiveAudienceRoleReporter *_reporter;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WCFinderLiveAudienceRoleReporter *reporter; // @synthesize reporter=_reporter;
@property(retain, nonatomic) WCTableViewManager *tableViewManager; // @synthesize tableViewManager=_tableViewManager;
@property(nonatomic) __weak id <WCFinderTrumpetSelectViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)finderLiveUpdateIdentity;
- (void)finderLiveIdentityChange;
- (void)selectedLiveIdentity:(id)arg1;
- (id)makeSectionSeparator;
- (void)editTrumpetAccount;
- (void)deleteTrumpetAccount;
- (void)createTrumpetAccount;
- (void)addAccountSection;
- (void)reloadTableView;
- (void)configureTableView;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dealloc;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

