//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface WCFinderConfigActionSheetParamModel : NSObject
{
    _Bool _isAuthor;
    _Bool _hasDislike;
    _Bool _isNeedSticyTop;
    _Bool _isAuthorAtMentionRemoveScene;
    _Bool _collectionFlag;
    _Bool _hiddenDeleteItem;
    unsigned long long _feedScreenStyle;
    unsigned long long _viewerScene;
}

@property(nonatomic) unsigned long long viewerScene; // @synthesize viewerScene=_viewerScene;
@property(nonatomic) unsigned long long feedScreenStyle; // @synthesize feedScreenStyle=_feedScreenStyle;
@property(nonatomic) _Bool hiddenDeleteItem; // @synthesize hiddenDeleteItem=_hiddenDeleteItem;
@property(nonatomic) _Bool collectionFlag; // @synthesize collectionFlag=_collectionFlag;
@property(nonatomic) _Bool isAuthorAtMentionRemoveScene; // @synthesize isAuthorAtMentionRemoveScene=_isAuthorAtMentionRemoveScene;
@property(nonatomic) _Bool isNeedSticyTop; // @synthesize isNeedSticyTop=_isNeedSticyTop;
@property(nonatomic) _Bool hasDislike; // @synthesize hasDislike=_hasDislike;
@property(nonatomic) _Bool isAuthor; // @synthesize isAuthor=_isAuthor;
- (id)initWithViewerScene:(unsigned long long)arg1 feedScreenStyle:(unsigned long long)arg2;

@end

