//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSMutableArray, NSObject, WCFinderLiveNoticeView, WCFinderProfileEventView;

@interface WCFinderProfileCardContainer : UIView
{
    NSObject *_delegate;
    WCFinderLiveNoticeView *_liveNoticeView;
    WCFinderProfileEventView *_eventView;
    NSMutableArray *_lineViews;
    NSMutableArray *_elements;
}

+ (double)displayHeightWithIsAuthor:(_Bool)arg1 extInfo:(id)arg2 width:(double)arg3;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *elements; // @synthesize elements=_elements;
@property(retain, nonatomic) NSMutableArray *lineViews; // @synthesize lineViews=_lineViews;
@property(retain, nonatomic) WCFinderProfileEventView *eventView; // @synthesize eventView=_eventView;
@property(retain, nonatomic) WCFinderLiveNoticeView *liveNoticeView; // @synthesize liveNoticeView=_liveNoticeView;
@property(nonatomic) __weak NSObject *delegate; // @synthesize delegate=_delegate;
- (void)unInstallViews:(id)arg1;
- (void)installElements:(id)arg1;
- (void)ensureLinesWithCount:(long long)arg1;
- (void)layoutLinesWithCount:(id)arg1;
- (void)updateElementsLayout:(id)arg1;
- (id)displayedViews;
- (void)updateWithIsAuthor:(_Bool)arg1 extInfo:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

