//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCFinderMusicFeedVM.h"

@class WCFinderFeedDraft;

@interface WCFinderMusicFeedDraftVM : WCFinderMusicFeedVM
{
    WCFinderFeedDraft *_draftVM;
}

+ (id)feedVMWithContentVM:(id)arg1 drfatVM:(id)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) WCFinderFeedDraft *draftVM; // @synthesize draftVM=_draftVM;

@end

