//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSMutableArray, UILabel;
@protocol WCFinderStreamHeaderActionProtocol;

@interface WCFinderProfileMiniAppsView : UIView
{
    id <WCFinderStreamHeaderActionProtocol> _delegate;
    UILabel *_titleLabel;
    NSMutableArray *_itemViews;
}

+ (double)displayHeightWithMiniAppInfos:(id)arg1 width:(double)arg2;
+ (id)formatTitle:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *itemViews; // @synthesize itemViews=_itemViews;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak id <WCFinderStreamHeaderActionProtocol> delegate; // @synthesize delegate=_delegate;
- (void)onClickMiniApp:(id)arg1;
- (void)onClickItemView:(id)arg1;
- (void)addItemWithAppInfo:(id)arg1;
- (void)updateMiniAppInfos:(id)arg1;
- (void)sizeToFit;
- (void)layoutGridViews;
- (void)layoutSubviews;
- (void)updateHiddenStatus;
- (id)initWithFrame:(struct CGRect)arg1;

@end

