//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WCTTableCoding-Protocol.h"

@class FinderEventInfo, FinderLiveNoticeInfo, FinderUserPagePoi, FinderWxAppInfo, NSString, WCFinderMiniAppInfoArray, WCFinderProfileBrandInfoArray, WCFinderStreamProfileExtInfoTagArray, WCFinderStreamProfileExtInfoTopicInfoArray;

@interface WCFinderStreamProfileExtInfo : NSObject <WCTTableCoding>
{
    NSString *_finderUsername;
    WCFinderStreamProfileExtInfoTagArray *_userTags;
    unsigned long long _fansCount;
    unsigned long long _friendFollowCount;
    double _cacheTime;
    FinderWxAppInfo *_storeAppInfo;
    FinderLiveNoticeInfo *_liveNoticeInfo;
    WCFinderStreamProfileExtInfoTopicInfoArray *_topics;
    WCFinderMiniAppInfoArray *_miniAppInfos;
    WCFinderProfileBrandInfoArray *_brandInfos;
    FinderUserPagePoi *_poiInfo;
    FinderEventInfo *_eventInfo;
}

+ (void)__wcdb_index_12:(struct WCTBinding *)arg1;
+ (void)__wcdb_column_constraint_11:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)__wcdb_synthesize_10:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)miniAppInfos;
+ (const struct WCTProperty *)__wcdb_synthesize_9:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)eventInfo;
+ (const struct WCTProperty *)__wcdb_synthesize_8:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)brandInfos;
+ (const struct WCTProperty *)__wcdb_synthesize_7:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)topics;
+ (const struct WCTProperty *)__wcdb_synthesize_6:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)liveNoticeInfo;
+ (const struct WCTProperty *)__wcdb_synthesize_5:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)storeAppInfo;
+ (const struct WCTProperty *)__wcdb_synthesize_4:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)cacheTime;
+ (const struct WCTProperty *)__wcdb_synthesize_3:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)userTags;
+ (const struct WCTProperty *)__wcdb_synthesize_2:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)friendFollowCount;
+ (const struct WCTProperty *)__wcdb_synthesize_1:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)fansCount;
+ (const struct WCTProperty *)__wcdb_synthesize_0:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)finderUsername;
+ (id)__wcdbtyper;
+ (const SyntaxList_7f15fe8c *)allProperties;
+ (const struct WCTBinding *)objectRelationalMapping;
- (void).cxx_destruct;
@property(retain, nonatomic) FinderEventInfo *eventInfo; // @synthesize eventInfo=_eventInfo;
@property(retain, nonatomic) FinderUserPagePoi *poiInfo; // @synthesize poiInfo=_poiInfo;
@property(retain, nonatomic) WCFinderProfileBrandInfoArray *brandInfos; // @synthesize brandInfos=_brandInfos;
@property(retain, nonatomic) WCFinderMiniAppInfoArray *miniAppInfos; // @synthesize miniAppInfos=_miniAppInfos;
@property(retain, nonatomic) WCFinderStreamProfileExtInfoTopicInfoArray *topics; // @synthesize topics=_topics;
@property(retain, nonatomic) FinderLiveNoticeInfo *liveNoticeInfo; // @synthesize liveNoticeInfo=_liveNoticeInfo;
@property(retain, nonatomic) FinderWxAppInfo *storeAppInfo; // @synthesize storeAppInfo=_storeAppInfo;
@property(nonatomic) double cacheTime; // @synthesize cacheTime=_cacheTime;
@property(nonatomic) unsigned long long friendFollowCount; // @synthesize friendFollowCount=_friendFollowCount;
@property(nonatomic) unsigned long long fansCount; // @synthesize fansCount=_fansCount;
@property(retain, nonatomic) WCFinderStreamProfileExtInfoTagArray *userTags; // @synthesize userTags=_userTags;
@property(retain, nonatomic) NSString *finderUsername; // @synthesize finderUsername=_finderUsername;
- (id)description;
- (void)SetMiniAppInfos:(id)arg1;
- (id)GetMiniAppInfos;
- (id)GetBrandInfos;
- (void)SetBrandInfos:(id)arg1;
- (void)updateTopics:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

// Remaining properties
@property(nonatomic) _Bool isAutoIncrement;
@property(nonatomic) long long lastInsertedRowID;

@end

