//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCFinderContentTableViewCellDelegate-Protocol.h"

@class WCFinderContentHeaderView, WCFinderFeedContentVM;

@protocol WCFinderContentHeaderViewDelegate <WCFinderContentTableViewCellDelegate>
- (void)onCommentContentTableViewCell:(WCFinderContentHeaderView *)arg1 longPressContentAction:(WCFinderFeedContentVM *)arg2 rect:(struct CGRect)arg3;
- (void)onClickUserHead:(WCFinderFeedContentVM *)arg1;
@end

