//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView, UILabel;
@protocol WCFinderProfileEventViewDelegate;

@interface WCFinderProfileEventView : UIView
{
    id <WCFinderProfileEventViewDelegate> _delegate;
    UIImageView *_iconView;
    UILabel *_titleLabel;
    UILabel *_feedCountLabel;
    UIView *_verticalLineView;
    UILabel *_timeTipsLabel;
    UIView *_rightArrowView;
}

+ (double)heightWithEventInfo:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) UIView *rightArrowView; // @synthesize rightArrowView=_rightArrowView;
@property(retain, nonatomic) UILabel *timeTipsLabel; // @synthesize timeTipsLabel=_timeTipsLabel;
@property(retain, nonatomic) UIView *verticalLineView; // @synthesize verticalLineView=_verticalLineView;
@property(retain, nonatomic) UILabel *feedCountLabel; // @synthesize feedCountLabel=_feedCountLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
@property(nonatomic) __weak id <WCFinderProfileEventViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)onTap;
- (void)layoutUI;
- (void)updateWithEventInfo:(id)arg1;
- (void)initSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

