//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class FinderMiniAppInfo, MMWebImageView, UILabel;

@interface WCFinderProfileMiniAppsGridsItemView : UIView
{
    UIView *_backgroundView;
    MMWebImageView *_iconView;
    UILabel *_titleLabel;
    FinderMiniAppInfo *_userinfo;
}

- (void).cxx_destruct;
@property(retain, nonatomic) FinderMiniAppInfo *userinfo; // @synthesize userinfo=_userinfo;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) MMWebImageView *iconView; // @synthesize iconView=_iconView;
@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
- (void)layoutSubviews;
- (id)initWithTitle:(id)arg1 iconUrl:(id)arg2 userInfo:(id)arg3;

@end

