//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FinderLiveAdInfo, FinderLiveAppMsgAlertInfo, FinderLiveAppMsgLotteryDrawInfo, FinderLiveAppMsgToastInfo, FinderLiveContact, FinderLiveErrorPage, FinderLiveMicInfo, FinderLiveShopWindowAdItem, FinderLiveShopWindowProductItem, FinderLiveUserInfo, FinderLocation, LiveSdkInfo, MMFinderLiveAnchorStatusItem, MMFinderLiveRedPacketReceiveInfo, MMFinderLiveRedPacketSendInfo, MMFinderLiveRewardAppMsgInfo, MMFinderLiveTaskId, NSArray, NSData, NSDictionary, NSError, NSMutableArray, NSString, WCFinderContact, WCFinderDataItem, WCFinderLiveInfo;

@protocol WCFinderLiveExt <NSObject>

@optional
- (void)onGetFinderLiveRedPacketsWithTaskId:(MMFinderLiveTaskId *)arg1 redPacketInfos:(NSArray *)arg2;
- (void)onGetFinderLiveAppMessageWithTaskId:(MMFinderLiveTaskId *)arg1 receiveRedPacketInfo:(MMFinderLiveRedPacketReceiveInfo *)arg2;
- (void)onGetFinderLiveAppMessageWithTaskId:(MMFinderLiveTaskId *)arg1 sendRedPacketInfo:(MMFinderLiveRedPacketSendInfo *)arg2;
- (void)onFinderLiveAnchorStatusUpdated:(MMFinderLiveAnchorStatusItem *)arg1;
- (void)onGetHighlightCheerUserWithFinderContacts:(NSMutableArray *)arg1;
- (void)onGetFinderLiveToastInfoWithTaskId:(MMFinderLiveTaskId *)arg1 toastInfo:(FinderLiveAppMsgToastInfo *)arg2;
- (void)onGetFinderLiveAlertInfoWithTaskId:(MMFinderLiveTaskId *)arg1 alertInfo:(FinderLiveAppMsgAlertInfo *)arg2;
- (void)onGetFinderLiveRewardAppMsgWithTaskId:(MMFinderLiveTaskId *)arg1 rewardAppMsgInfo:(MMFinderLiveRewardAppMsgInfo *)arg2;
- (void)onGetFinderLiveLotteryDrawInfoWithTaskId:(MMFinderLiveTaskId *)arg1 lotteryDrawInfo:(FinderLiveAppMsgLotteryDrawInfo *)arg2;
- (void)onGetFinderLiveLotteryInfoWithTaskId:(MMFinderLiveTaskId *)arg1 liveLotteryInfos:(NSArray *)arg2 lotteryDrawInfos:(NSArray *)arg3 fromJoinLive:(_Bool)arg4;
- (void)onGetFinderLiveAnchorConnectMicStatusInfoWithTaskId:(MMFinderLiveTaskId *)arg1 fromFinderContact:(WCFinderContact *)arg2 connectMicFinderContact:(WCFinderContact *)arg3 status:(long long)arg4 sessionId:(NSString *)arg5 sequence:(unsigned long long)arg6 sdkUserId:(NSString *)arg7;
- (void)onGetFinderLiveAnchorCloseMicMessageWithTaskId:(MMFinderLiveTaskId *)arg1 fromFinderContact:(WCFinderContact *)arg2 sessionId:(NSString *)arg3;
- (void)onGetFinderLiveAnchorAcceptMicMessageWithTaskId:(MMFinderLiveTaskId *)arg1 fromFinderContact:(WCFinderContact *)arg2 sdkUserId:(NSString *)arg3 sdkRoomId:(unsigned int)arg4 sdkPkSign:(NSString *)arg5 sessionId:(NSString *)arg6 sequence:(unsigned long long)arg7;
- (void)onGetFinderLiveAnchorApplyMicMessageWithTaskId:(MMFinderLiveTaskId *)arg1 fromFinderContact:(WCFinderContact *)arg2 sdkUserId:(NSString *)arg3 sdkRoomId:(unsigned int)arg4 sessionId:(NSString *)arg5;
- (void)onGetFinderLiveCloseMicMessageWithTaskId:(MMFinderLiveTaskId *)arg1 fromFinderContact:(WCFinderContact *)arg2 sessionId:(NSString *)arg3;
- (void)onGetFinderLiveAcceptMicMessageWithTaskId:(MMFinderLiveTaskId *)arg1 fromFinderContact:(WCFinderContact *)arg2 connectMicFinderContact:(WCFinderContact *)arg3 liveSdkInfo:(LiveSdkInfo *)arg4 withVideo:(_Bool)arg5 expiredTime:(unsigned long long)arg6 sdkUserId:(NSString *)arg7 sessionId:(NSString *)arg8 sequence:(unsigned long long)arg9;
- (void)onGetFinderLiveApplyMicMessageWithTaskId:(MMFinderLiveTaskId *)arg1 fromFinderContact:(WCFinderContact *)arg2 withVideo:(_Bool)arg3 confirmTime:(unsigned int)arg4 sdkUserId:(NSString *)arg5 sessionId:(NSString *)arg6;
- (void)finderLiveHoverSnsTimelineSwitchChanged:(_Bool)arg1;
- (void)onTopComment:(NSError *)arg1 taskId:(MMFinderLiveTaskId *)arg2;
- (void)onFinderLiveNoticeWithNoticeId:(NSString *)arg1 reserveStateChanged:(unsigned long long)arg2;
- (void)onFinderLiveVerifyRealNameForComment;
- (void)onFinderLiveVerified:(NSError *)arg1 isNameVerified:(_Bool)arg2 withVerifyUrl:(NSString *)arg3 withEntryType:(long long)arg4;
- (void)onGetFinderContact:(NSError *)arg1 contact:(FinderLiveContact *)arg2;
- (void)onFinderLiveUpdateCommentSingleEnable;
- (void)onFinderLiveUpdateCommentEnable;
- (void)onGetFinderLiveSetAnchorStatusResult:(NSError *)arg1 anchorStatus:(MMFinderLiveAnchorStatusItem *)arg2 extraInfo:(id)arg3 liveId:(unsigned long long)arg4;
- (void)onGetFinderLiveBanComment:(NSError *)arg1 enableComment:(_Bool)arg2 forUserName:(NSString *)arg3;
- (void)onDeleteFinderShopWindowProduct:(NSError *)arg1 productId:(unsigned long long)arg2;
- (void)onSetTopFinderShopWindowProduct:(NSError *)arg1 productId:(unsigned long long)arg2;
- (void)onEndPromoteAdResult:(NSError *)arg1;
- (void)onSendPromoteAdResult:(NSError *)arg1;
- (void)onEndPromoteProductResult:(NSError *)arg1;
- (void)onSendPromoteProductResult:(NSError *)arg1;
- (void)onGetFinderShopWindowProduct:(NSError *)arg1 productsInfo:(NSDictionary *)arg2;
- (void)onFinderGetLiveOnlineMember:(NSError *)arg1 taskId:(MMFinderLiveTaskId *)arg2 onlineContacts:(NSArray *)arg3 rewardTotalAmountInHeat:(unsigned long long)arg4 onlineMemberCount:(unsigned int)arg5 selfLiveContact:(FinderLiveContact *)arg6;
- (void)onFinderLiveCloseWithTid:(NSString *)arg1;
- (void)onPostFinderLiveLike:(NSError *)arg1 taskId:(MMFinderLiveTaskId *)arg2 attendLottery:(_Bool)arg3;
- (void)onPostFinderLiveMessage:(NSError *)arg1 taskId:(MMFinderLiveTaskId *)arg2 attendLottery:(_Bool)arg3;
- (void)onGetFinderLiveMessage:(NSError *)arg1 taskId:(MMFinderLiveTaskId *)arg2 onlineContacts:(NSArray *)arg3 msgList:(NSArray *)arg4 finderLiveInfo:(WCFinderLiveInfo *)arg5 onlineCount:(unsigned int)arg6 liveInfoEnable:(_Bool)arg7 liveClosed:(_Bool)arg8 liveExtFlag:(unsigned int)arg9 onlineViewCount:(unsigned int)arg10 nextRequestInterval:(unsigned int)arg11 currentLikeCount:(unsigned long long)arg12;
- (void)onGetFinderLiveError:(NSError *)arg1 finderLiveInfo:(WCFinderLiveInfo *)arg2;
- (void)onCancelFinderLiveError:(NSError *)arg1 finderDataItem:(WCFinderDataItem *)arg2;
- (void)onCloseFinderLiveError:(NSError *)arg1 finderDataItem:(WCFinderDataItem *)arg2 liveDurationSeconds:(unsigned int)arg3 liveAudiencesNum:(unsigned int)arg4 liveBeLikedNum:(unsigned int)arg5 liveNewFansNum:(unsigned int)arg6;
- (void)onJoinFinderLiveError:(NSError *)arg1 finderDataItem:(WCFinderDataItem *)arg2 liveCookies:(NSData *)arg3 liveSDKInfo:(LiveSdkInfo *)arg4 finderLiveInfo:(WCFinderLiveInfo *)arg5 promotingProduct:(FinderLiveShopWindowProductItem *)arg6 userInfo:(FinderLiveUserInfo *)arg7 liveMicInfo:(FinderLiveMicInfo *)arg8 joinLiveTips:(NSString *)arg9 templateInfoArr:(NSArray *)arg10 joinLiveFlag:(unsigned int)arg11 liveLocation:(FinderLocation *)arg12 liveAdInfo:(FinderLiveAdInfo *)arg13 promotingAd:(FinderLiveShopWindowAdItem *)arg14;
- (void)onCreateFinderLiveError:(NSError *)arg1 finderDataItem:(WCFinderDataItem *)arg2 errorPage:(FinderLiveErrorPage *)arg3;
@end

