//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionReusableView.h>

@class NSString, UILabel, UIView;

@interface WCRedEnvelopesExpiredSkinViewControllerFooter : UICollectionReusableView
{
    NSString *_limitedWording;
    UIView *_lineViewLeft;
    UIView *_lineViewRight;
    UILabel *_limitedWordingLabel;
    UIView *_limitedWordingView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIView *limitedWordingView; // @synthesize limitedWordingView=_limitedWordingView;
@property(retain, nonatomic) UILabel *limitedWordingLabel; // @synthesize limitedWordingLabel=_limitedWordingLabel;
@property(retain, nonatomic) UIView *lineViewRight; // @synthesize lineViewRight=_lineViewRight;
@property(retain, nonatomic) UIView *lineViewLeft; // @synthesize lineViewLeft=_lineViewLeft;
@property(nonatomic) NSString *limitedWording; // @synthesize limitedWording=_limitedWording;
- (void)updateView;
- (void)setupLimitedWording:(id)arg1;
- (void)layoutSubviews;

@end

