//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUserService.h"

#import "MMServiceProtocol-Protocol.h"

@class NSString, WCTDatabase, WCTTable;

@interface WCTextStateDB : MMUserService <MMServiceProtocol>
{
    WCTDatabase *_database;
    WCTTable *_likeInfoTable;
    WCTTable *_likeInfoCacheTable;
    WCTTable *_readInfoTable;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WCTTable *readInfoTable; // @synthesize readInfoTable=_readInfoTable;
@property(retain, nonatomic) WCTTable *likeInfoCacheTable; // @synthesize likeInfoCacheTable=_likeInfoCacheTable;
@property(retain, nonatomic) WCTTable *likeInfoTable; // @synthesize likeInfoTable=_likeInfoTable;
@property(retain, nonatomic) WCTDatabase *database; // @synthesize database=_database;
- (void)clearExpiredReadInfo;
- (_Bool)setReadForTopicId:(id)arg1 members:(id)arg2;
- (_Bool)setReadForTextStateId:(id)arg1 topicId:(id)arg2 expiredTime:(unsigned int)arg3;
- (_Bool)isTextStateRead:(id)arg1;
- (void)willRecoverDatabase;
- (void)didRecoverDatabase;
- (_Bool)deleteExistLikeInfosWithInfo:(id)arg1 table:(id)arg2;
- (id)getLikeInfoWithStateID:(id)arg1 limit:(unsigned int)arg2;
- (unsigned int)getSelfTopicChatNumber;
- (void)setSelfTopicChatNumber:(unsigned int)arg1;
- (void)makeAllLikeInfoToUnNotify;
- (void)makeAllLikeInfoToUnRead;
- (void)makeAllLikeInfoToRead;
- (id)getAllLikeInfoWithTime:(unsigned int)arg1 limit:(unsigned int)arg2;
- (id)getAllLikeInfoLimit:(unsigned int)arg1;
- (unsigned int)getUnReadNotifyCount;
- (unsigned int)getUnReadMessageCount;
- (id)getUnReadLikeInfo;
- (id)getAllUnReadLikeInfo;
- (_Bool)addTextStateLikeInfo:(id)arg1;
- (void)setLikeCountWithStateId:(id)arg1 likeCount:(unsigned int)arg2;
- (unsigned int)getLikeCountWithStateId:(id)arg1;
- (void)closeDB;
- (void)createReadInfoTable;
- (_Bool)createLikeInfoCacheTable;
- (_Bool)createLikeInfoTable;
- (void)createTables;
- (_Bool)reloadDataBase;
- (void)onServiceInit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

