//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSMutableArray;

@interface WDAudienceLabel : UIView
{
    unsigned int _curIndex;
    NSMutableArray *_labelList;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned int curIndex; // @synthesize curIndex=_curIndex;
@property(retain, nonatomic) NSMutableArray *labelList; // @synthesize labelList=_labelList;
- (void)updateWithText:(id)arg1;
- (void)layoutSubviews;
- (void)initLabel;
- (void)initSubviews;
- (id)init;

@end

