//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

@class CustomVisualEffectView, UIButton, UILabel, UIView;

@interface WDCommonViewController : MMUIViewController
{
    CDUnknownBlockType _closeBlock;
    CustomVisualEffectView *_blurView;
    UIButton *_back;
    UIView *_navView;
    UILabel *_customTitle;
    UILabel *_titleTail;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *titleTail; // @synthesize titleTail=_titleTail;
@property(retain, nonatomic) UILabel *customTitle; // @synthesize customTitle=_customTitle;
@property(retain, nonatomic) UIView *navView; // @synthesize navView=_navView;
@property(retain, nonatomic) UIButton *back; // @synthesize back=_back;
@property(retain, nonatomic) CustomVisualEffectView *blurView; // @synthesize blurView=_blurView;
@property(copy, nonatomic) CDUnknownBlockType closeBlock; // @synthesize closeBlock=_closeBlock;
- (void)viewDidBePoped:(_Bool)arg1;
- (void)onReturnClick;
- (void)removeNavTitleTail;
- (void)setNavTitleTail:(id)arg1 color:(id)arg2;
- (void)setNavTitle:(id)arg1;
- (long long)preferredStatusBarStyle;
- (void)initCommon:(id)arg1;
- (void)viewDidLoad;

@end

