//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class UIColor;

@interface WDColorConfig : NSObject
{
    unsigned int _startSecond;
    unsigned int _endSecond;
    UIColor *_color1;
    UIColor *_color2;
    UIColor *_color3;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned int endSecond; // @synthesize endSecond=_endSecond;
@property(nonatomic) unsigned int startSecond; // @synthesize startSecond=_startSecond;
@property(retain, nonatomic) UIColor *color3; // @synthesize color3=_color3;
@property(retain, nonatomic) UIColor *color2; // @synthesize color2=_color2;
@property(retain, nonatomic) UIColor *color1; // @synthesize color1=_color1;

@end

