//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CADisplayLink, NSArray, UIButton, UILabel;
@protocol WDColorPickerViewDelegate;

@interface WDColorPickerView : UIView
{
    id <WDColorPickerViewDelegate> _delegate;
    UIView *_pickerArea;
    NSArray *_colorList;
    NSArray *_colorBtnList;
    UIView *_accessoryBar;
    UILabel *_instructionLabel;
    UIButton *_cancelBtn;
    UILabel *_forbidLabel;
    long long _nextTimeAvailableInMS;
    CADisplayLink *_displayLink;
}

+ (double)pickerHeightWithAccessoryBar:(_Bool)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) CADisplayLink *displayLink; // @synthesize displayLink=_displayLink;
@property(nonatomic) long long nextTimeAvailableInMS; // @synthesize nextTimeAvailableInMS=_nextTimeAvailableInMS;
@property(retain, nonatomic) UILabel *forbidLabel; // @synthesize forbidLabel=_forbidLabel;
@property(retain, nonatomic) UIButton *cancelBtn; // @synthesize cancelBtn=_cancelBtn;
@property(retain, nonatomic) UILabel *instructionLabel; // @synthesize instructionLabel=_instructionLabel;
@property(retain, nonatomic) UIView *accessoryBar; // @synthesize accessoryBar=_accessoryBar;
@property(retain, nonatomic) NSArray *colorBtnList; // @synthesize colorBtnList=_colorBtnList;
@property(retain, nonatomic) NSArray *colorList; // @synthesize colorList=_colorList;
@property(retain, nonatomic) UIView *pickerArea; // @synthesize pickerArea=_pickerArea;
@property(nonatomic) __weak id <WDColorPickerViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)hideAccessoryBar;
- (void)showAccessoryBarWithContent:(id)arg1;
- (_Bool)hasShowAccessoryBar;
- (_Bool)isAvailableNow;
- (void)onDisplayLinkCalled:(id)arg1;
- (void)disableUntilInMS:(long long)arg1;
- (_Bool)isSelected;
- (id)getSelectedColor;
- (void)markBtn:(id)arg1 selected:(_Bool)arg2;
- (void)cancel;
- (void)onCancelBtnClicked:(id)arg1;
- (void)onColorBtnClicked:(id)arg1;
- (void)layoutSubviews;
- (void)invalidateDisplayLink;
- (void)initDisplayLink;
- (void)initForbidLabel;
- (void)initAccessoryBar;
- (void)initPickerArea;
- (void)initSubviews;
- (void)initColorsList;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

