//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUserService.h"

#import "MMServiceProtocol-Protocol.h"

@class NSString, WCTDatabase, WCTTable;

@interface WDDataBaseMgr : MMUserService <MMServiceProtocol>
{
    WCTDatabase *_db;
    WCTTable *_tableCommonWishInfo;
    WCTTable *_tableFriendWishInfo;
    WCTTable *_tableLikeWishInfo;
    WCTTable *_tableLikedWish;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WCTTable *tableLikedWish; // @synthesize tableLikedWish=_tableLikedWish;
@property(retain, nonatomic) WCTTable *tableLikeWishInfo; // @synthesize tableLikeWishInfo=_tableLikeWishInfo;
@property(retain, nonatomic) WCTTable *tableFriendWishInfo; // @synthesize tableFriendWishInfo=_tableFriendWishInfo;
@property(retain, nonatomic) WCTTable *tableCommonWishInfo; // @synthesize tableCommonWishInfo=_tableCommonWishInfo;
@property(retain) WCTDatabase *db; // @synthesize db=_db;
- (_Bool)isMyLikeWish:(id)arg1;
- (_Bool)deleteLikedWish:(id)arg1;
- (_Bool)addLikedWish:(id)arg1;
- (void)updateLikeMsgOwnerWish:(id)arg1;
- (id)getLikeMessages;
- (id)getAllFriendWishes;
- (void)clearFriendWish;
- (_Bool)addFriendWishInfos:(id)arg1;
- (_Bool)deleteFriendWishInfoByID:(id)arg1;
- (_Bool)deleteCommonWishInfoByID:(id)arg1;
- (_Bool)addLikesMesssages:(id)arg1;
- (_Bool)addCommonWishInfos:(id)arg1;
- (_Bool)addCommonWishInfo:(id)arg1;
- (id)getAllCommonWishes;
- (id)getLastCommonWish;
- (void)clearCommonWish;
- (id)getWishInfoWithCordinatorSortByCreateTime:(unsigned long long)arg1 mapY:(unsigned long long)arg2;
- (id)getAllWishInfoByUserName:(id)arg1;
- (id)getCommonWishInfoByUserName:(id)arg1;
- (id)getCommonWishInfoByID:(id)arg1;
- (id)setupTableWithName:(id)arg1 tableClass:(Class)arg2;
- (void)willRecoverDatabase;
- (void)closeDB;
- (void)clearLocalData;
- (void)setupTable;
- (void)initDB;
- (void)onServiceInit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

