//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CustomVisualEffectView, UIButton, UILabel, WDRandomMeteorView;

@interface WDErrorInfoView : UIView
{
    CDUnknownBlockType _closeBlock;
    CDUnknownBlockType _profileBlock;
    CustomVisualEffectView *_blurView;
    UIButton *_back;
    UIView *_navView;
    UILabel *_title;
    WDRandomMeteorView *_randomMeteorView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WDRandomMeteorView *randomMeteorView; // @synthesize randomMeteorView=_randomMeteorView;
@property(retain, nonatomic) UILabel *title; // @synthesize title=_title;
@property(retain, nonatomic) UIView *navView; // @synthesize navView=_navView;
@property(retain, nonatomic) UIButton *back; // @synthesize back=_back;
@property(retain, nonatomic) CustomVisualEffectView *blurView; // @synthesize blurView=_blurView;
@property(copy, nonatomic) CDUnknownBlockType profileBlock; // @synthesize profileBlock=_profileBlock;
@property(copy, nonatomic) CDUnknownBlockType closeBlock; // @synthesize closeBlock=_closeBlock;
- (void)setNetworkError;
- (void)onProfile;
- (void)setEndLive;
- (double)randomFloatBetween:(double)arg1 with:(double)arg2;
- (void)generateMeteorImageView;
- (void)setWaitingStart;
- (void)setErrorType:(unsigned int)arg1;
- (void)onReturnClick;
- (id)initWithFrame:(struct CGRect)arg1;

@end

