//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class MMWebImageView, UIButton, WDCommonWishInfo;

@interface WDFootprintCanvasView : UIView
{
    WDCommonWishInfo *_wishInfo;
    UIButton *_bgView;
    MMWebImageView *_head;
}

- (void).cxx_destruct;
@property(retain, nonatomic) MMWebImageView *head; // @synthesize head=_head;
@property(retain, nonatomic) UIButton *bgView; // @synthesize bgView=_bgView;
@property(retain, nonatomic) WDCommonWishInfo *wishInfo; // @synthesize wishInfo=_wishInfo;
- (void)onHeadClick;
- (void)updatePixel:(id)arg1;
- (void)addCornerToSelfView:(id)arg1;
- (double)getBottomOffset;
- (id)initWithPixel:(id)arg1 head:(id)arg2;

@end

