//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class MMUIButton, MMUILabel, NSArray, NSString;
@protocol WDFootprintDelegate;

@interface WDFootprintDetail : UIView
{
    id <WDFootprintDelegate> _delegate;
    NSString *_nickName;
    NSArray *_userWishes;
    MMUIButton *_btnReturn;
    MMUILabel *_dateTime;
    MMUIButton *_btnDelete;
}

- (void).cxx_destruct;
@property(retain, nonatomic) MMUIButton *btnDelete; // @synthesize btnDelete=_btnDelete;
@property(retain, nonatomic) MMUILabel *dateTime; // @synthesize dateTime=_dateTime;
@property(retain, nonatomic) MMUIButton *btnReturn; // @synthesize btnReturn=_btnReturn;
@property(retain, nonatomic) NSArray *userWishes; // @synthesize userWishes=_userWishes;
@property(retain, nonatomic) NSString *nickName; // @synthesize nickName=_nickName;
@property(nonatomic) __weak id <WDFootprintDelegate> delegate; // @synthesize delegate=_delegate;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)updateInfo:(id)arg1;
- (void)layoutSubviews;
- (void)onDelete;
- (void)onClose;
- (void)updateFootprintData:(id)arg1;

@end

