//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QuartzCore/CAShapeLayer.h>

@interface WDGlowLayer : CAShapeLayer
{
    double _red;
    double _green;
    double _blue;
}

@property(nonatomic) double blue; // @synthesize blue=_blue;
@property(nonatomic) double green; // @synthesize green=_green;
@property(nonatomic) double red; // @synthesize red=_red;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithColor:(id)arg1 frame:(struct CGRect)arg2;

@end

