//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "IWeDrawManagerExt-Protocol.h"
#import "MMFinderLiveLogicDelegate-Protocol.h"
#import "MMLiveCommentViewDelegate-Protocol.h"
#import "MMLiveLikeDataMgrExt-Protocol.h"
#import "MMLiveLogicDelegate-Protocol.h"
#import "MMScrollActionSheetDelegate-Protocol.h"
#import "MiniTaskEdgeGestureHandlerDelegate-Protocol.h"
#import "UIViewControllerTransitioningDelegate-Protocol.h"
#import "WCActionSheetDelegate-Protocol.h"
#import "WCFinderLiveHalfScreenUtilControllerDelegate-Protocol.h"
#import "WCFinderTrumpetSelectViewControllerDelegate-Protocol.h"
#import "WDCanvasDelegate-Protocol.h"
#import "WDDismissAnimatedTransitioningDelegate-Protocol.h"
#import "WDFlashWishViewDelegate-Protocol.h"
#import "WDIntroPageViewDelegate-Protocol.h"
#import "WDLikesViewControllerDelegate-Protocol.h"
#import "WDLiveLogicDelegate-Protocol.h"
#import "WDScrollActionSheetDelegate-Protocol.h"
#import "WDSubTitleContainerDelegate-Protocol.h"
#import "WDTopMenuViewDelegate-Protocol.h"

@class CAEmitterLayer, ForwardMessageLogicController, MMAudienceLiveLikePlayUtil, MMFinderLiveCommentInputEmoticonView, MMLiveLikeAnimationUtil, MMLiveLikeButton, MMUIActivityIndicatorView, MMUIButton, MMWebImageView, MiniTaskNavEdgeGestureHandler, NSString, PostFestivalWishResp, UIButton, UIImageView, UIPanGestureRecognizer, UIView, WCFinderLiveHalfScreenUtilController, WDAudienceLabel, WDCanvas, WDChoosePositionMaskView, WDCommonWishInfo, WDCordinator, WDErrorInfoView, WDFlashContainerView, WDFlashWishView, WDFootprintDetail, WDImageUploadLogic, WDLikesDetail, WDLiveCommentView, WDLiveLogic, WDLiveTask, WDMusicPlayerLogic, WDPixel, WDStateConfirmView, WDSubTitleContainerView, WDTopMenuView, WDWishBrowserView;

@interface WDHomeViewController : MMUIViewController <MMLiveCommentViewDelegate, MMFinderLiveLogicDelegate, WDLiveLogicDelegate, WCFinderLiveHalfScreenUtilControllerDelegate, WCActionSheetDelegate, MMLiveLikeDataMgrExt, MMLiveLogicDelegate, WDTopMenuViewDelegate, WDCanvasDelegate, MMScrollActionSheetDelegate, IWeDrawManagerExt, WDIntroPageViewDelegate, WDScrollActionSheetDelegate, WCFinderTrumpetSelectViewControllerDelegate, WDFlashWishViewDelegate, WDSubTitleContainerDelegate, WDLikesViewControllerDelegate, MiniTaskEdgeGestureHandlerDelegate, WDDismissAnimatedTransitioningDelegate, UIViewControllerTransitioningDelegate>
{
    MMAudienceLiveLikePlayUtil *_audienceLikePlayUtil;
    MMLiveLikeAnimationUtil *_audienceSelflikeAnimationUtil;
    MMLiveLikeAnimationUtil *_audienceOtherLikeAnimationUtil;
    UIView *_likeAnimationWrapper;
    _Bool _canvasUseNearestInterpolation;
    _Bool _liveError;
    _Bool _hasDestroyed;
    _Bool _initWithCache;
    _Bool _isInProfile;
    _Bool _isFlashing;
    _Bool _subTitleRunning;
    _Bool _canWishNow;
    _Bool _isInLive;
    unsigned int _scene;
    unsigned int _statePublishTimes;
    UIButton *_headBtn;
    WDAudienceLabel *_audienceLabel;
    WDWishBrowserView *_browserView;
    UIView *_canvasMaskView;
    UIView *_testRectView;
    WDCordinator *_lastCordinatorForTestRect;
    WDPixel *_lastTappedPixel;
    WDMusicPlayerLogic *_playerLoigc;
    WDFlashWishView *_selectedFlashWishView;
    MMUIActivityIndicatorView *_canvasLoadingIndicatorView;
    WDErrorInfoView *_errorView;
    CAEmitterLayer *_fairyWandsLayer;
    CAEmitterLayer *_fairyWandsLayerBackup;
    UIPanGestureRecognizer *_fairyWandsPanGesture;
    unsigned long long _viewMode;
    WDCanvas *_canvasLogic;
    WDTopMenuView *_topMenuView;
    MMUIButton *_wishBtn;
    MMWebImageView *_authIconView;
    UIImageView *_stateBubbleView;
    MMUIButton *_stateBtn;
    WDFlashContainerView *_flashContainer;
    WDSubTitleContainerView *_subtitleContainer;
    WDFootprintDetail *_footprintContainer;
    WDLikesDetail *_likesContainer;
    WDImageUploadLogic *_imageUploadLogic;
    ForwardMessageLogicController *_forwardLogic;
    UIImageView *_pressGifImg;
    WDChoosePositionMaskView *_choosePosMaskView;
    WDPixel *_selectedPixel;
    WDFlashWishView *_selectFlashWishView;
    WDCommonWishInfo *_postWishInfo;
    UIImageView *_selectStarImgView;
    UIImageView *_wishFrontImageView;
    WDStateConfirmView *_stateConfirmView;
    WDLiveTask *_liveTask;
    WDLiveLogic *_liveLogic;
    NSString *_onlineDesc;
    NSString *_seenDesc;
    NSString *_likeDesc;
    MMLiveLikeButton *_likeButton;
    long long _likeCount;
    WDLiveCommentView *_commentView;
    MMFinderLiveCommentInputEmoticonView *_inputEmoticonView;
    WCFinderLiveHalfScreenUtilController *_verifyAndPolicyView;
    PostFestivalWishResp *_postWishResp;
    MiniTaskNavEdgeGestureHandler *_leftEdgeGestureHandler;
}

- (void).cxx_destruct;
@property(retain, nonatomic) MiniTaskNavEdgeGestureHandler *leftEdgeGestureHandler; // @synthesize leftEdgeGestureHandler=_leftEdgeGestureHandler;
@property(retain, nonatomic) PostFestivalWishResp *postWishResp; // @synthesize postWishResp=_postWishResp;
@property(retain, nonatomic) WCFinderLiveHalfScreenUtilController *verifyAndPolicyView; // @synthesize verifyAndPolicyView=_verifyAndPolicyView;
@property(retain, nonatomic) MMFinderLiveCommentInputEmoticonView *inputEmoticonView; // @synthesize inputEmoticonView=_inputEmoticonView;
@property(retain, nonatomic) WDLiveCommentView *commentView; // @synthesize commentView=_commentView;
@property(nonatomic) long long likeCount; // @synthesize likeCount=_likeCount;
@property(retain, nonatomic) MMLiveLikeButton *likeButton; // @synthesize likeButton=_likeButton;
@property(retain, nonatomic) NSString *likeDesc; // @synthesize likeDesc=_likeDesc;
@property(retain, nonatomic) NSString *seenDesc; // @synthesize seenDesc=_seenDesc;
@property(retain, nonatomic) NSString *onlineDesc; // @synthesize onlineDesc=_onlineDesc;
@property(nonatomic) _Bool isInLive; // @synthesize isInLive=_isInLive;
@property(retain, nonatomic) WDLiveLogic *liveLogic; // @synthesize liveLogic=_liveLogic;
@property(retain, nonatomic) WDLiveTask *liveTask; // @synthesize liveTask=_liveTask;
@property(nonatomic) unsigned int statePublishTimes; // @synthesize statePublishTimes=_statePublishTimes;
@property(retain, nonatomic) WDStateConfirmView *stateConfirmView; // @synthesize stateConfirmView=_stateConfirmView;
@property(nonatomic) _Bool canWishNow; // @synthesize canWishNow=_canWishNow;
@property(retain, nonatomic) UIImageView *wishFrontImageView; // @synthesize wishFrontImageView=_wishFrontImageView;
@property(retain, nonatomic) UIImageView *selectStarImgView; // @synthesize selectStarImgView=_selectStarImgView;
@property(retain, nonatomic) WDCommonWishInfo *postWishInfo; // @synthesize postWishInfo=_postWishInfo;
@property(retain, nonatomic) WDFlashWishView *selectFlashWishView; // @synthesize selectFlashWishView=_selectFlashWishView;
@property(retain, nonatomic) WDPixel *selectedPixel; // @synthesize selectedPixel=_selectedPixel;
@property(retain, nonatomic) WDChoosePositionMaskView *choosePosMaskView; // @synthesize choosePosMaskView=_choosePosMaskView;
@property(retain, nonatomic) UIImageView *pressGifImg; // @synthesize pressGifImg=_pressGifImg;
@property(retain, nonatomic) ForwardMessageLogicController *forwardLogic; // @synthesize forwardLogic=_forwardLogic;
@property(retain, nonatomic) WDImageUploadLogic *imageUploadLogic; // @synthesize imageUploadLogic=_imageUploadLogic;
@property(retain, nonatomic) WDLikesDetail *likesContainer; // @synthesize likesContainer=_likesContainer;
@property(retain, nonatomic) WDFootprintDetail *footprintContainer; // @synthesize footprintContainer=_footprintContainer;
@property(nonatomic) _Bool subTitleRunning; // @synthesize subTitleRunning=_subTitleRunning;
@property(retain, nonatomic) WDSubTitleContainerView *subtitleContainer; // @synthesize subtitleContainer=_subtitleContainer;
@property(nonatomic) _Bool isFlashing; // @synthesize isFlashing=_isFlashing;
@property(retain, nonatomic) WDFlashContainerView *flashContainer; // @synthesize flashContainer=_flashContainer;
@property(retain, nonatomic) MMUIButton *stateBtn; // @synthesize stateBtn=_stateBtn;
@property(retain, nonatomic) UIImageView *stateBubbleView; // @synthesize stateBubbleView=_stateBubbleView;
@property(retain, nonatomic) MMWebImageView *authIconView; // @synthesize authIconView=_authIconView;
@property(retain, nonatomic) MMUIButton *wishBtn; // @synthesize wishBtn=_wishBtn;
@property(retain, nonatomic) WDTopMenuView *topMenuView; // @synthesize topMenuView=_topMenuView;
@property(retain, nonatomic) WDCanvas *canvasLogic; // @synthesize canvasLogic=_canvasLogic;
@property(nonatomic) unsigned long long viewMode; // @synthesize viewMode=_viewMode;
@property(retain, nonatomic) UIPanGestureRecognizer *fairyWandsPanGesture; // @synthesize fairyWandsPanGesture=_fairyWandsPanGesture;
@property(nonatomic) _Bool isInProfile; // @synthesize isInProfile=_isInProfile;
@property(nonatomic) unsigned int scene; // @synthesize scene=_scene;
@property(retain, nonatomic) CAEmitterLayer *fairyWandsLayerBackup; // @synthesize fairyWandsLayerBackup=_fairyWandsLayerBackup;
@property(retain, nonatomic) CAEmitterLayer *fairyWandsLayer; // @synthesize fairyWandsLayer=_fairyWandsLayer;
@property(nonatomic) _Bool initWithCache; // @synthesize initWithCache=_initWithCache;
@property(retain, nonatomic) WDErrorInfoView *errorView; // @synthesize errorView=_errorView;
@property(retain, nonatomic) MMUIActivityIndicatorView *canvasLoadingIndicatorView; // @synthesize canvasLoadingIndicatorView=_canvasLoadingIndicatorView;
@property(retain, nonatomic) WDFlashWishView *selectedFlashWishView; // @synthesize selectedFlashWishView=_selectedFlashWishView;
@property(retain, nonatomic) WDMusicPlayerLogic *playerLoigc; // @synthesize playerLoigc=_playerLoigc;
@property(retain, nonatomic) WDPixel *lastTappedPixel; // @synthesize lastTappedPixel=_lastTappedPixel;
@property(retain, nonatomic) WDCordinator *lastCordinatorForTestRect; // @synthesize lastCordinatorForTestRect=_lastCordinatorForTestRect;
@property(retain, nonatomic) UIView *testRectView; // @synthesize testRectView=_testRectView;
@property(retain, nonatomic) UIView *canvasMaskView; // @synthesize canvasMaskView=_canvasMaskView;
@property(retain, nonatomic) WDWishBrowserView *browserView; // @synthesize browserView=_browserView;
@property(retain, nonatomic) WDAudienceLabel *audienceLabel; // @synthesize audienceLabel=_audienceLabel;
@property(retain, nonatomic) UIButton *headBtn; // @synthesize headBtn=_headBtn;
@property(nonatomic) _Bool hasDestroyed; // @synthesize hasDestroyed=_hasDestroyed;
@property(nonatomic) _Bool liveError; // @synthesize liveError=_liveError;
@property(nonatomic) _Bool canvasUseNearestInterpolation; // @synthesize canvasUseNearestInterpolation=_canvasUseNearestInterpolation;
- (void)onForbiddenStatusChange:(unsigned int)arg1;
- (void)onSeenDescChange:(id)arg1;
- (void)onOnLineDescChange:(id)arg1;
- (void)onLikeDescChange:(id)arg1;
- (void)onLiveNeedToStopNow;
- (void)onNewMessage:(id)arg1;
- (void)onWishConfigLiveChange:(id)arg1;
- (void)onNetworkError;
- (void)onFestivalInitError:(int)arg1;
- (void)onFestivalWishInit:(id)arg1;
- (void)scrollActionSheetWillDismiss:(id)arg1;
- (void)onFinderTrumpetSelectViewLiveIdentityDidChanged:(unsigned int)arg1;
- (void)onFinderTrumpetSelectViewLiveIdentityWillChange:(unsigned int)arg1;
- (void)gotoTrumpetSelectViewController;
- (void)scrollActionSheet:(id)arg1 didSelecteItem:(id)arg2;
- (void)onFlashWishViewDestroyed:(id)arg1;
- (void)onFlashWishViewTapped:(id)arg1;
- (void)onLikesClose;
- (void)onOtherLikeDetail:(id)arg1;
- (void)onSubTitleClicked:(id)arg1 point:(struct CGPoint)arg2;
- (void)onCurrentWishDetail:(id)arg1;
- (void)moveToFootprint:(id)arg1;
- (_Bool)tryCreateCanvas;
- (_Bool)isCanvasAtMinimumLevel;
- (void)canvasDidFinishLoadFirstFrame:(id)arg1;
- (void)canvas:(id)arg1 endScroll:(struct CGPoint)arg2;
- (void)canvas:(id)arg1 endZoom:(double)arg2;
- (void)canvas:(id)arg1 didScroll:(struct CGPoint)arg2;
- (void)canvas:(id)arg1 didZoomToScale:(double)arg2;
- (void)canvas:(id)arg1 didSelectPixel:(id)arg2;
- (void)canvas:(id)arg1 didTapOnCanvas:(id)arg2;
- (void)onTopMenuViewBtnClicked:(unsigned long long)arg1;
- (void)initWhenConfigInited:(id)arg1;
- (void)updateAudienceLabel;
- (void)showTestRect:(id)arg1;
- (void)updatePressGifPosition;
- (void)showPressGifAtPoint:(struct CGPoint)arg1;
- (void)showPressGifAtCordinator:(id)arg1;
- (void)updateSelectedFlashWishViewPosition;
- (void)updateSelectStarImgViewPosition;
- (void)openWishWithInfo:(id)arg1 fromPoint:(struct CGPoint)arg2 fromProfile:(_Bool)arg3 completion:(CDUnknownBlockType)arg4 closeCallback:(CDUnknownBlockType)arg5;
- (void)openWishWithInfo:(id)arg1 fromProfile:(_Bool)arg2;
- (void)onActionSheetOpenUrl:(id)arg1;
- (void)showMenuActionSheet;
- (struct CGPoint)screenPointFromPixel:(id)arg1;
- (void)onWishBtnTouchCanceled:(id)arg1;
- (void)onWishBtnPressed:(id)arg1;
- (void)onWishBtnClicked:(id)arg1;
- (void)onStateBtnClick;
- (id)getRandomColorComponents;
- (void)fairyWandBackToLiveMode;
- (void)canvasDidEndFairyWandMagic:(id)arg1;
- (void)onMaskViewPan:(id)arg1;
- (void)onMaskViewTap;
- (void)minimizeAfterGoToProfile;
- (void)onHeadBtnClicked:(id)arg1;
- (void)setFairyWandsEnable:(_Bool)arg1;
- (void)setStarShiningEffectEnable:(_Bool)arg1;
- (void)enableTapGesture:(_Bool)arg1;
- (void)switchFootprintVisible:(_Bool)arg1;
- (void)switchSubtitlePageVisible:(_Bool)arg1;
- (void)switchFlashingWishPageVisible:(_Bool)arg1;
- (void)switchTopMenuVisible:(_Bool)arg1;
- (void)removeselectFlashWishView;
- (void)checkRemoveselectFlashWishView;
- (void)switchLiveElementVisible:(_Bool)arg1;
- (void)switchViewMode:(unsigned long long)arg1;
- (_Bool)isViewVisible:(id)arg1;
- (void)initBGMDebugView;
- (void)initTestRectView;
- (void)initStateBtn;
- (void)initWishBtn;
- (id)genPressGifImg;
- (id)generateEmitterLayer;
- (void)initFairyWands;
- (void)initCanvasView;
- (void)initAudienceLabel;
- (void)initAuthIconView;
- (void)initHeadBtn;
- (void)initTopMenuView;
- (void)onIntroPageViewClose:(id)arg1;
- (void)showIntroView;
- (void)viewDidBeDismissed:(_Bool)arg1;
- (void)viewDidBePresented:(_Bool)arg1;
- (void)initSubviews;
- (void)didEnterBackground:(id)arg1;
- (void)willEnterForeground:(id)arg1;
- (_Bool)useTransparentNavibar;
- (void)viewWillLayoutSubviews;
- (void)viewDidBePoped:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)checkInsertCanvasViewBack;
- (void)viewWillAppear:(_Bool)arg1;
- (void)initFlashAndSubtitle;
- (void)viewDidLoad;
- (void)internalDestroy;
- (void)dealloc;
- (void)internalInit:(unsigned int)arg1;
- (id)init;
- (id)initWithScene:(unsigned int)arg1;
- (void)pauseFlash:(_Bool)arg1;
- (id)createWishFlash:(id)arg1;
- (void)onDetail:(id)arg1;
- (void)stopFlushWishes;
- (void)beginFlashWishes;
- (void)updateFlashViewPort;
- (void)initFlashView;
- (_Bool)canShowFlashWishes;
- (id)genStarWishImg;
- (void)onDonateTipsPageViewClose:(id)arg1;
- (void)onDonateTipsPageViewOpenUrl:(id)arg1 url:(id)arg2;
- (_Bool)showStateGuideWithWishAfterDelay:(double)arg1;
- (_Bool)checkShowDonateTips;
- (void)delayCheckShowDonateTips;
- (void)onEnterNormalScaleAfterWish;
- (void)onStartWeChatPayVerifyProcess:(long long)arg1;
- (void)onEditViewFinishCommitReturn:(id)arg1 resp:(id)arg2;
- (void)onEditViewCancelReturn;
- (void)updateWishBtn;
- (void)showChoosePositionMaskViewWithText:(id)arg1;
- (void)enterEditPageWithChoosePixel:(id)arg1;
- (void)zoomInCanvasToChoosePos:(id)arg1;
- (void)startWish;
- (void)pauseSubtitle:(_Bool)arg1;
- (void)startOneWishFlash:(id)arg1 offset:(double)arg2;
- (void)stopSubtitle:(_Bool)arg1;
- (void)startSubtitle:(double)arg1;
- (void)initSubTitle:(double)arg1;
- (_Bool)canShowSubTitle;
- (void)OnForwardMessageCancel:(id)arg1;
- (void)OnForwardMessageSend:(id)arg1;
- (id)getCurrentViewController;
- (void)onShareCurrentCanvasToWC:(id)arg1;
- (void)shareToFriend:(id)arg1;
- (id)getFinderDataItem;
- (void)handleShareAction:(unsigned int)arg1 thumbImg:(id)arg2;
- (_Bool)state_shouldShowCardView;
- (_Bool)state_shouldRotateStateIcon;
- (id)state_genGradientImageForState;
- (void)onTextStatePublished;
- (void)onWDStateConfirmViewCancelBtnClicked:(id)arg1;
- (void)onWDStateConfirmViewConfirmBtnClicked:(id)arg1;
- (void)state_showTextStatePublishViewControllerWithWishInfo:(id)arg1;
- (void)state_hideAndBackToLive;
- (void)state_showStateConfirmViewWithWishInfo:(id)arg1;
- (void)onDismissAnimatedTransitioningEnd;
- (void)onDismissAnimatedTransitioningBegin:(double)arg1;
- (struct CGRect)getFloatViewVisibleFrame;
- (void)performMinimizationTansitionAnimation:(id)arg1;
- (void)onMiniInteractiveTransitionDidEnd:(id)arg1 isComplete:(_Bool)arg2;
- (void)onMiniInteractiveTransitionWillEnd:(id)arg1 isComplete:(_Bool)arg2;
- (void)onMiniInteractiveTransitionChanged:(id)arg1 progress:(double)arg2;
- (_Bool)shouldBlockMiniInteractiveTransitionComplete:(id)arg1;
- (_Bool)shouldMiniInteractiveTransitionBegin:(id)arg1;
- (void)onMiniInteractiveTransitionBegin:(id)arg1;
- (id)interactionControllerForDismissal:(id)arg1;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (void)onMinimizeHomeViewController;
- (void)setupLeftScreenEdgeGestureHandler;
- (void)setupTransition;
- (_Bool)invokeExposeComplainWithExtraData:(id)arg1 extraQuery:(id)arg2;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)onLikeContactListUpdate:(id)arg1;
- (void)onDisplayLikeCountUpdate:(unsigned long long)arg1 withTaskId:(id)arg2 forRole:(long long)arg3;
- (void)onWCFinderLiveHalfScreenConfirmButtonClicked:(long long)arg1;
- (void)onGetLiveInfo;
- (void)onGetLiveOnlineCount:(unsigned int)arg1;
- (void)onLiveHalfScreenViewEnd:(_Bool)arg1 fromScene:(long long)arg2;
- (void)onShowLiveHalfScreenViewFromScene:(long long)arg1;
- (void)onFinderDataItemUpdated;
- (void)onJoinLive:(id)arg1;
- (double)getTopWidgetsBottom;
- (void)onBackViewDidTaped;
- (void)updateButtonHiddenForInputViewShowChange:(_Bool)arg1;
- (double)getVisibleHeight;
- (id)liveTaskId;
- (void)updateLikeCountDisplayForAudience;
- (void)recordSelfLike;
- (void)initlikeButton;
- (id)likeAnimationWrapper;
- (id)likeMgr;
- (id)audienceOtherLikeAnimationUtil;
- (id)audienceSelflikeAnimationUtil;
- (id)audienceLikePlayUtil;
- (void)updateAuthInfo;
- (void)showActionSheetForCommentItemFromAudience:(id)arg1;
- (void)joinLive;
- (void)configLiveTask;
- (void)onExitLive;
- (void)onEnterLive;
- (void)initCommentView;
- (void)updateLiveId:(id)arg1 liveUserName:(id)arg2 objectId:(id)arg3 objectNonceId:(id)arg4;
- (void)initLiveTask;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

