//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class UILabel, WDWishTopicItem;

@interface WDHotWishPanelBtn : UIButton
{
    WDWishTopicItem *_item;
    double _maxWidth;
    UILabel *_contentLabel;
    UILabel *_countLabel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *countLabel; // @synthesize countLabel=_countLabel;
@property(retain, nonatomic) UILabel *contentLabel; // @synthesize contentLabel=_contentLabel;
@property(nonatomic) double maxWidth; // @synthesize maxWidth=_maxWidth;
@property(retain, nonatomic) WDWishTopicItem *item; // @synthesize item=_item;
- (void)layoutSubviews;
- (void)initSubview;
- (id)genCountStr:(unsigned int)arg1;
- (void)setItem:(id)arg1 maxWidth:(double)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

