//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "IWebviewResourceManagerExt-Protocol.h"

@class NSMutableDictionary, NSString;

@interface WDImageUploadLogic : NSObject <IWebviewResourceManagerExt>
{
    NSMutableDictionary *_dicUploadingTask;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableDictionary *dicUploadingTask; // @synthesize dicUploadingTask=_dicUploadingTask;
- (void)onLocalResourceUploadFinishedWithoutMediaId:(id)arg1 LocalId:(id)arg2 FileUrl:(id)arg3 ErrCode:(int)arg4;
- (void)onLocalResourceUploadFinished:(id)arg1 SvrId:(id)arg2 ErrCode:(int)arg3;
- (void)uploadImageWithMMImage:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)uploadImageWithFilePath:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)uploadImage:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

