//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CustomVisualEffectView, RichTextView, UIButton, UIImageView;
@protocol WDIntroPageViewDelegate;

@interface WDIntroPageView : UIView
{
    _Bool _isTransitioning;
    id <WDIntroPageViewDelegate> _delegate;
    CustomVisualEffectView *_cardView;
    UIImageView *_imageView;
    RichTextView *_contentLabel;
    UIButton *_confirmBtn;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool isTransitioning; // @synthesize isTransitioning=_isTransitioning;
@property(retain, nonatomic) UIButton *confirmBtn; // @synthesize confirmBtn=_confirmBtn;
@property(retain, nonatomic) RichTextView *contentLabel; // @synthesize contentLabel=_contentLabel;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) CustomVisualEffectView *cardView; // @synthesize cardView=_cardView;
@property(nonatomic) __weak id <WDIntroPageViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)onConfirmBtnClick;
- (void)layoutCardViewPos;
- (id)getStringForImageLabel;
- (void)layoutSubviews;
- (void)dismissWithAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)showFromPoint:(struct CGPoint)arg1 completion:(CDUnknownBlockType)arg2;
- (void)initSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

