//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UILabel;
@protocol WDIntroViewDelegate;

@interface WDIntroView : UIView
{
    id <WDIntroViewDelegate> _delegate;
    UILabel *_msgLabel;
    UIButton *_wishBtn;
    UIButton *_skipBtn;
}

+ (id)genWishButton;
- (void).cxx_destruct;
@property(retain, nonatomic) UIButton *skipBtn; // @synthesize skipBtn=_skipBtn;
@property(retain, nonatomic) UIButton *wishBtn; // @synthesize wishBtn=_wishBtn;
@property(retain, nonatomic) UILabel *msgLabel; // @synthesize msgLabel=_msgLabel;
@property(nonatomic) __weak id <WDIntroViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)onSkipBtnClicked:(id)arg1;
- (void)onWishBtnClicked:(id)arg1;
- (void)layoutSubviews;
- (void)initSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

