//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface WDLauncher : NSObject
{
}

+ (_Bool)resolveExternalConflicts;
+ (unsigned int)getEntryStatus;
+ (void)showWDHomeViewFromScene:(unsigned int)arg1 animated:(_Bool)arg2 curNavigationController:(id)arg3;
+ (void)showWDHomeViewFromScene:(unsigned int)arg1 curNavigationController:(id)arg2;
+ (void)showWDHomeViewFromScene:(unsigned int)arg1 animated:(_Bool)arg2;

@end

