//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMFinderLiveCommentView.h"

@interface WDLiveCommentView : MMFinderLiveCommentView
{
}

- (struct CGRect)notifyContentViewRectRelativeToWindow;
- (struct CGRect)commentTableRectRelativeToWindow;
- (void)tryAppendAnchorNoticeDataItem;
- (_Bool)isCommentItemSupportDisplay:(id)arg1;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)initWithTaskId:(id)arg1 assumeAudienceCommentEnabled:(_Bool)arg2 delegate:(id)arg3 inputEmoticonView:(id)arg4;

@end

