//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "WDLikeCellDelegate-Protocol.h"

@class CAGradientLayer, MMPageSheetAdapter, NSArray, NSMutableArray, NSString, UILabel, UITableView, UIView;
@protocol WDLikesViewControllerDelegate;

@interface WDLikesViewController : MMUIViewController <UITableViewDelegate, UITableViewDataSource, WDLikeCellDelegate>
{
    _Bool _showDetail;
    id <WDLikesViewControllerDelegate> _delegate;
    NSArray *_backgroundGradientLayerColors;
    UIView *_customNavBar;
    UILabel *_titleTail;
    MMPageSheetAdapter *_adapter;
    UITableView *_tableView;
    NSMutableArray *_oldLikeWishes;
    NSMutableArray *_freshLikeWishes;
    CAGradientLayer *_gradientLayer;
}

- (void).cxx_destruct;
@property(retain, nonatomic) CAGradientLayer *gradientLayer; // @synthesize gradientLayer=_gradientLayer;
@property(nonatomic) _Bool showDetail; // @synthesize showDetail=_showDetail;
@property(retain, nonatomic) NSMutableArray *freshLikeWishes; // @synthesize freshLikeWishes=_freshLikeWishes;
@property(retain, nonatomic) NSMutableArray *oldLikeWishes; // @synthesize oldLikeWishes=_oldLikeWishes;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak MMPageSheetAdapter *adapter; // @synthesize adapter=_adapter;
@property(retain, nonatomic) UILabel *titleTail; // @synthesize titleTail=_titleTail;
@property(retain, nonatomic) UIView *customNavBar; // @synthesize customNavBar=_customNavBar;
@property(retain, nonatomic) NSArray *backgroundGradientLayerColors; // @synthesize backgroundGradientLayerColors=_backgroundGradientLayerColors;
@property(nonatomic) __weak id <WDLikesViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)mmNavigationController:(id)arg1 animationControllerForOperation:(long long)arg2 fromViewController:(id)arg3 toViewController:(id)arg4;
- (void)onLikeCellHeadImgClick:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dealloc;
- (_Bool)shouldInteractivePop;
- (_Bool)useTransparentNavibar;
- (void)pageSheetDidClose:(id)arg1;
- (void)viewDidLoad;
- (void)onClose;
- (void)updateCustomNav;
- (void)initLeftButton;
- (void)setBackgroundColor:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

