//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UIImageView, UILabel;

@interface WDLiveView : UIView
{
    UIButton *_bgView;
    UIImageView *_watchingBg;
    UIImageView *_watchingLogo;
    UILabel *_watchingNum;
    UIImageView *_liveLogo;
    UILabel *_liveName;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *liveName; // @synthesize liveName=_liveName;
@property(retain, nonatomic) UIImageView *liveLogo; // @synthesize liveLogo=_liveLogo;
@property(retain, nonatomic) UILabel *watchingNum; // @synthesize watchingNum=_watchingNum;
@property(retain, nonatomic) UIImageView *watchingLogo; // @synthesize watchingLogo=_watchingLogo;
@property(retain, nonatomic) UIImageView *watchingBg; // @synthesize watchingBg=_watchingBg;
@property(retain, nonatomic) UIButton *bgView; // @synthesize bgView=_bgView;
- (void)onClick;
- (id)initWithFrame:(struct CGRect)arg1;

@end

