//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMFinderLiveTaskId.h"

@class NSString;

@interface WDLiveTaskId : MMFinderLiveTaskId
{
    unsigned long long _objectid;
    NSString *_objectNonceId;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *objectNonceId; // @synthesize objectNonceId=_objectNonceId;
@property(nonatomic) unsigned long long objectid; // @synthesize objectid=_objectid;

@end

