//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMFinderLiveLogic.h"

@protocol WDLiveLogicDelegate;

@interface WDLiveLogic : MMFinderLiveLogic
{
    unsigned int _onlineCount;
    unsigned int _totalParticipantCount;
    id <WDLiveLogicDelegate> _customLiveDelegate;
    unsigned long long _likeCount;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned int totalParticipantCount; // @synthesize totalParticipantCount=_totalParticipantCount;
@property(nonatomic) unsigned int onlineCount; // @synthesize onlineCount=_onlineCount;
@property(nonatomic) unsigned long long likeCount; // @synthesize likeCount=_likeCount;
@property(nonatomic) __weak id <WDLiveLogicDelegate> customLiveDelegate; // @synthesize customLiveDelegate=_customLiveDelegate;
- (void)fetchDetailNewDataItem;
- (id)liveTask;
- (void)onJoinFinderLiveError:(id)arg1 finderDataItem:(id)arg2 liveCookies:(id)arg3 liveSDKInfo:(id)arg4 finderLiveInfo:(id)arg5 promotingProduct:(id)arg6 userInfo:(id)arg7 liveMicInfo:(id)arg8 joinLiveTips:(id)arg9 templateInfoArr:(id)arg10 joinLiveFlag:(unsigned int)arg11 liveLocation:(id)arg12 liveAdInfo:(id)arg13 promotingAd:(id)arg14;

@end

