//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMFinderLiveTask.h"

@class WDLiveTaskId;

@interface WDLiveTask : MMFinderLiveTask
{
}

- (_Bool)handleConflictWithNewFinderDataItems:(id)arg1 selectedIndex:(id)arg2 navigationController:(id)arg3 tabType:(int)arg4 commentScene:(unsigned long long)arg5;
- (_Bool)handleConflictWithNewLive:(id)arg1 navigationController:(id)arg2;
- (_Bool)resolveExternalConflicts;
@property(readonly, nonatomic) WDLiveTaskId *wdTaskId;
- (unsigned long long)objectID;
- (id)objectNonceID;
- (id)createNewTaskId;
- (id)initWithRoleType:(long long)arg1 liveId:(unsigned long long)arg2 andAnchorId:(id)arg3;

@end

