//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "IWAAudioPlayerDelegate-Protocol.h"
#import "IWeDrawManagerExt-Protocol.h"

@class MMTimer, NSMutableArray, NSString, UILabel, WAAudioPlayer;

@interface WDMusicPlayerLogic : NSObject <IWeDrawManagerExt, IWAAudioPlayerDelegate>
{
    _Bool _isObservering;
    unsigned int _currentIndex;
    unsigned int _totalDuration;
    unsigned int _curState;
    unsigned int _playFlag;
    WAAudioPlayer *_player;
    NSMutableArray *_musicList;
    double _startTime;
    MMTimer *_timer;
    UILabel *_debugLabel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *debugLabel; // @synthesize debugLabel=_debugLabel;
@property(retain, nonatomic) MMTimer *timer; // @synthesize timer=_timer;
@property(nonatomic) unsigned int playFlag; // @synthesize playFlag=_playFlag;
@property(nonatomic) unsigned int curState; // @synthesize curState=_curState;
@property(nonatomic) _Bool isObservering; // @synthesize isObservering=_isObservering;
@property(nonatomic) double startTime; // @synthesize startTime=_startTime;
@property(nonatomic) unsigned int totalDuration; // @synthesize totalDuration=_totalDuration;
@property(nonatomic) unsigned int currentIndex; // @synthesize currentIndex=_currentIndex;
@property(retain, nonatomic) NSMutableArray *musicList; // @synthesize musicList=_musicList;
@property(retain, nonatomic) WAAudioPlayer *player; // @synthesize player=_player;
- (void)onTimerUpdate;
- (void)onMusicPlayFlagChange:(unsigned int)arg1;
- (void)onPlayerStateChange:(long long)arg1 audioId:(id)arg2 errCode:(long long)arg3 errMsg:(id)arg4;
- (void)stop;
- (void)pause;
- (void)play;
- (void)activeAudioSession;
- (void)initAndPlayMusicList:(id)arg1;
- (void)onMusicListChange:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

