//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "ILinkEventExt-Protocol.h"

@class NSString, RichTextView, UILabel;
@protocol WDScrollActionSheetHeaderViewDelegate;

@interface WDScrollActionSheetHeaderView : UIView <ILinkEventExt>
{
    NSString *_content;
    UILabel *_titleLabel;
    RichTextView *_contentLabel;
    UIView *_lineView;
    id <WDScrollActionSheetHeaderViewDelegate> _delegate;
}

+ (double)headerViewHeightForContent:(id)arg1 InWidth:(double)arg2;
- (void).cxx_destruct;
@property(nonatomic) __weak id <WDScrollActionSheetHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIView *lineView; // @synthesize lineView=_lineView;
@property(retain, nonatomic) RichTextView *contentLabel; // @synthesize contentLabel=_contentLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
- (void)onLinkClicked:(id)arg1 withRect:(struct CGRect)arg2;
- (void)layoutSubviews;
- (void)initSubviews;
- (id)initWithFrame:(struct CGRect)arg1 content:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

