//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIGestureRecognizerDelegate-Protocol.h"

@class CAGradientLayer, CustomVisualEffectView, MMUIButton, MMWebImageView, NSString, RichTextView, UIButton, UIImageView, UILabel, WDCommonWishInfo;
@protocol WDStateConfirmViewDelegate;

@interface WDStateConfirmView : UIView <UIGestureRecognizerDelegate>
{
    _Bool _isAnimating;
    _Bool _shouldRotateIcon;
    _Bool _shouldShowCard;
    WDCommonWishInfo *_wishInfo;
    id <WDStateConfirmViewDelegate> _delegate;
    UIView *_containerView;
    MMUIButton *_backBtn;
    CAGradientLayer *_gradientLayer;
    UIImageView *_titleImageView;
    RichTextView *_titleLabel;
    RichTextView *_msgTextView;
    UIView *_stateCardView;
    MMWebImageView *_headImgView;
    UILabel *_nicknameLabel;
    UIImageView *_luckyIconImgView;
    UILabel *_timeLabel;
    UILabel *_stateCardContentLabel;
    UIButton *_confirmBtn;
    UIButton *_cancelBtn;
    CustomVisualEffectView *_effectView;
}

+ (id)genGradientLayerWithSize:(struct CGSize)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) CustomVisualEffectView *effectView; // @synthesize effectView=_effectView;
@property(nonatomic) _Bool shouldShowCard; // @synthesize shouldShowCard=_shouldShowCard;
@property(nonatomic) _Bool shouldRotateIcon; // @synthesize shouldRotateIcon=_shouldRotateIcon;
@property(nonatomic) _Bool isAnimating; // @synthesize isAnimating=_isAnimating;
@property(retain, nonatomic) UIButton *cancelBtn; // @synthesize cancelBtn=_cancelBtn;
@property(retain, nonatomic) UIButton *confirmBtn; // @synthesize confirmBtn=_confirmBtn;
@property(retain, nonatomic) UILabel *stateCardContentLabel; // @synthesize stateCardContentLabel=_stateCardContentLabel;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) UIImageView *luckyIconImgView; // @synthesize luckyIconImgView=_luckyIconImgView;
@property(retain, nonatomic) UILabel *nicknameLabel; // @synthesize nicknameLabel=_nicknameLabel;
@property(retain, nonatomic) MMWebImageView *headImgView; // @synthesize headImgView=_headImgView;
@property(retain, nonatomic) UIView *stateCardView; // @synthesize stateCardView=_stateCardView;
@property(retain, nonatomic) RichTextView *msgTextView; // @synthesize msgTextView=_msgTextView;
@property(retain, nonatomic) RichTextView *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *titleImageView; // @synthesize titleImageView=_titleImageView;
@property(retain, nonatomic) CAGradientLayer *gradientLayer; // @synthesize gradientLayer=_gradientLayer;
@property(retain, nonatomic) MMUIButton *backBtn; // @synthesize backBtn=_backBtn;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(nonatomic) __weak id <WDStateConfirmViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) WDCommonWishInfo *wishInfo; // @synthesize wishInfo=_wishInfo;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)onTapBackground;
- (void)onCancelBtnClicked;
- (void)onConfirmBtnClicked;
- (void)updateTimeLabel;
- (void)updateWithText:(id)arg1;
- (void)layoutSubviews;
- (void)initCancelBtn;
- (void)initConfirmBtn;
- (void)initStateCardContentLabel;
- (void)initStateCardTimeLabel;
- (void)initStateCardLuckyIconImgView;
- (void)initStateCardNicknameLabel;
- (void)initStateCardHeadImageView;
- (void)initStateCardView;
- (id)getStringForImageLabel;
- (void)initMsgTextView;
- (void)initTitleLabel;
- (void)initTitleImageView;
- (void)initBackBtn;
- (void)initContainerView;
- (void)initSubviews;
- (void)dismissWithAnimated:(_Bool)arg1;
- (void)showWithAnimated:(_Bool)arg1;
- (id)initWithWishInfo:(id)arg1 shouldRotateIcon:(_Bool)arg2 shouldShowCard:(_Bool)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

