//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class RichTextView, UILabel, WDCommonHeadImageView, WDCommonWishInfo;
@protocol WDSubTitleViewDelegate;

@interface WDSubTitleView : UIView
{
    id <WDSubTitleViewDelegate> _delegate;
    WDCommonWishInfo *_info;
    WDCommonHeadImageView *_head;
    UILabel *_name;
    RichTextView *_content;
    double _realLength;
    double _containerWidth;
    unsigned long long _lastClick;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long lastClick; // @synthesize lastClick=_lastClick;
@property(nonatomic) double containerWidth; // @synthesize containerWidth=_containerWidth;
@property(nonatomic) double realLength; // @synthesize realLength=_realLength;
@property(retain, nonatomic) RichTextView *content; // @synthesize content=_content;
@property(retain, nonatomic) UILabel *name; // @synthesize name=_name;
@property(retain, nonatomic) WDCommonHeadImageView *head; // @synthesize head=_head;
@property(retain, nonatomic) WDCommonWishInfo *info; // @synthesize info=_info;
@property(nonatomic) __weak id <WDSubTitleViewDelegate> delegate; // @synthesize delegate=_delegate;
- (double)getRealLength;
- (void)onNextTitle;
- (void)complete;
- (void)onClick:(id)arg1;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)startSubtitleMove;
- (id)initWithWish:(id)arg1 width:(double)arg2 offset:(double)arg3;

@end

