//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "WDSubTitleViewDelegate-Protocol.h"

@class MMTimer, NSArray, NSMutableSet, NSString;
@protocol WDSubTitleContainerDelegate;

@interface WDSubTitleContainerView : UIView <WDSubTitleViewDelegate>
{
    _Bool _stopped;
    _Bool _haveSelfNewWish;
    id <WDSubTitleContainerDelegate> _delegate;
    MMTimer *_timer;
    NSArray *_listWishes;
    long long _currentIdx;
    double _currentOffset;
    double _topMargin;
    double _maxHeight;
    NSMutableSet *_setWishes;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool haveSelfNewWish; // @synthesize haveSelfNewWish=_haveSelfNewWish;
@property(retain, nonatomic) NSMutableSet *setWishes; // @synthesize setWishes=_setWishes;
@property(nonatomic) double maxHeight; // @synthesize maxHeight=_maxHeight;
@property(nonatomic) double topMargin; // @synthesize topMargin=_topMargin;
@property(nonatomic) double currentOffset; // @synthesize currentOffset=_currentOffset;
@property(nonatomic) long long currentIdx; // @synthesize currentIdx=_currentIdx;
@property(retain, nonatomic) NSArray *listWishes; // @synthesize listWishes=_listWishes;
@property(retain, nonatomic) MMTimer *timer; // @synthesize timer=_timer;
@property(nonatomic) __weak id <WDSubTitleContainerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)pause:(_Bool)arg1;
- (void)onNextTitle:(id)arg1;
- (void)onComplete:(id)arg1;
- (void)onClick:(id)arg1 point:(struct CGPoint)arg2;
- (id)createWishFlash:(id)arg1 offset:(double)arg2;
- (void)onTimer;
- (void)checkSubtitleSpeed:(long long)arg1;
- (void)stopSubtitle:(_Bool)arg1;
- (void)startSubtitle:(double)arg1;
- (void)setPosition:(double)arg1;
- (void)onFriendWishesChange:(id)arg1;
- (void)onPostMyWish:(id)arg1;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

