//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray;
@protocol WDTopMenuViewDelegate;

@interface WDTopMenuView : UIView
{
    id <WDTopMenuViewDelegate> _delegate;
    NSArray *_leftBtnList;
    NSArray *_rightBtnList;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *rightBtnList; // @synthesize rightBtnList=_rightBtnList;
@property(retain, nonatomic) NSArray *leftBtnList; // @synthesize leftBtnList=_leftBtnList;
@property(nonatomic) __weak id <WDTopMenuViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)layoutSubviews;
- (void)onBtnClicked:(id)arg1;
- (id)getImageNameWithBtnType:(unsigned long long)arg1;
- (void)updateAllBtns;
- (double)getFirstBtnX;
- (void)showRedDot:(_Bool)arg1 buttonType:(unsigned long long)arg2 side:(unsigned long long)arg3;
- (void)updateMenuViewWithBtnTypeList:(id)arg1 toSide:(unsigned long long)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

