//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface WDUtility : NSObject
{
}

+ (void)taptic;
+ (id)locationStrOfWishInfo:(id)arg1;
+ (id)parseAudienceNumToReadableString:(unsigned int)arg1;
+ (id)translateMusicList:(id)arg1;
+ (id)translateLikeMessage:(id)arg1;
+ (id)translateWishList:(id)arg1 excludeDel:(_Bool)arg2;
+ (id)translateWish:(id)arg1;
+ (void)motionizeView:(id)arg1 minimumRelativePoint:(struct CGPoint)arg2 maximumRelativePoint:(struct CGPoint)arg3;
+ (id)getStarImages;
+ (_Bool)isVersionChanged;
+ (id)saveImageWithDataToFile:(id)arg1;
+ (id)convertRGB2HexStrWithR:(unsigned int)arg1 g:(unsigned int)arg2 b:(unsigned int)arg3;
+ (id)convertUIntColor2HexStr:(unsigned long long)arg1;
+ (void)convertHexStr:(id)arg1 toR:(int *)arg2 g:(int *)arg3 b:(int *)arg4;
+ (id)getDefaultColor;
+ (id)uint2Color:(unsigned long long)arg1;
+ (unsigned long long)color2Uint:(id)arg1;
+ (unsigned int)currentTimeInSeconds;
+ (id)getFrendContacts;
+ (id)getLocalResourceId;
+ (id)localImageDirPath;
+ (id)WDHeadImageDirPath;
+ (id)WDCanvasImageDirPath;
+ (id)WDTempImageDirPath;
+ (id)WDDatabasePath;
+ (id)WDBaseDirPath;

@end

