//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class MMUIButton, UIButton, UIImage, WDUISlider;
@protocol WDVerticalSliderDelegate;

@interface WDVerticalSlider : UIView
{
    _Bool _isMinimized;
    _Bool _isDragging;
    id <WDVerticalSliderDelegate> _delegate;
    UIButton *_entryBtn;
    WDUISlider *_slider;
    MMUIButton *_zoomInBtn;
    MMUIButton *_zoomOutBtn;
    UIImage *_thumbImageForMax;
    UIImage *_thumbImageForMin;
    UIImage *_minTrackImageForMax;
    UIImage *_minTrackImageForMin;
    UIImage *_maxTrackImageForMax;
    UIImage *_maxTrackImageForMin;
    double _entryValue;
    struct CGPoint _entryPoint;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool isDragging; // @synthesize isDragging=_isDragging;
@property(nonatomic) double entryValue; // @synthesize entryValue=_entryValue;
@property(nonatomic) struct CGPoint entryPoint; // @synthesize entryPoint=_entryPoint;
@property(retain, nonatomic) UIImage *maxTrackImageForMin; // @synthesize maxTrackImageForMin=_maxTrackImageForMin;
@property(retain, nonatomic) UIImage *maxTrackImageForMax; // @synthesize maxTrackImageForMax=_maxTrackImageForMax;
@property(retain, nonatomic) UIImage *minTrackImageForMin; // @synthesize minTrackImageForMin=_minTrackImageForMin;
@property(retain, nonatomic) UIImage *minTrackImageForMax; // @synthesize minTrackImageForMax=_minTrackImageForMax;
@property(retain, nonatomic) UIImage *thumbImageForMin; // @synthesize thumbImageForMin=_thumbImageForMin;
@property(retain, nonatomic) UIImage *thumbImageForMax; // @synthesize thumbImageForMax=_thumbImageForMax;
@property(retain, nonatomic) MMUIButton *zoomOutBtn; // @synthesize zoomOutBtn=_zoomOutBtn;
@property(retain, nonatomic) MMUIButton *zoomInBtn; // @synthesize zoomInBtn=_zoomInBtn;
@property(retain, nonatomic) WDUISlider *slider; // @synthesize slider=_slider;
@property(nonatomic) _Bool isMinimized; // @synthesize isMinimized=_isMinimized;
@property(retain, nonatomic) UIButton *entryBtn; // @synthesize entryBtn=_entryBtn;
@property(nonatomic) __weak id <WDVerticalSliderDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) double value;
- (void)onSliderValueChanged;
- (void)onZoomOutBtnClicked;
- (void)onZoomInBtnClicked;
- (void)onEntryBtnDraging:(id)arg1 withEvent:(id)arg2;
- (void)onEntryBtnBeginDrag:(id)arg1 withEvent:(id)arg2;
- (void)onEntryBtnTouchEnd:(id)arg1 withEvent:(id)arg2;
- (void)onEntryBtnTouched:(id)arg1 withEvent:(id)arg2;
- (void)maximizeSlider;
- (void)minimizeSlider;
- (void)onSliderTouchUp;
- (void)onSliderTouchDown;
- (void)restartTimer;
- (void)updateSliderLayout;
- (void)layoutSubviews;
- (void)updateThumbImage;
- (void)initSlider;
- (void)initZoomOutBtn;
- (void)initZoomInBtn;
- (void)initEntryBtn;
- (void)initSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

