//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMPageSheetBaseView.h"

@class CustomVisualEffectView, MMUIButton, NSArray, NSMutableArray, UIImage, UIImageView, UILabel;
@protocol WDWishTopicHalfScreenViewDelegate;

@interface WDWishTopicHalfScreenView : MMPageSheetBaseView
{
    id <WDWishTopicHalfScreenViewDelegate> _delegate;
    UIImage *_bgImage;
    UIImageView *_panelView;
    CustomVisualEffectView *_effectView;
    MMUIButton *_closeBtn;
    UILabel *_titleLabel;
    NSArray *_itemList;
    NSMutableArray *_btnList;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *btnList; // @synthesize btnList=_btnList;
@property(retain, nonatomic) NSArray *itemList; // @synthesize itemList=_itemList;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) MMUIButton *closeBtn; // @synthesize closeBtn=_closeBtn;
@property(retain, nonatomic) CustomVisualEffectView *effectView; // @synthesize effectView=_effectView;
@property(retain, nonatomic) UIImageView *panelView; // @synthesize panelView=_panelView;
@property(retain, nonatomic) UIImage *bgImage; // @synthesize bgImage=_bgImage;
@property(nonatomic) __weak id <WDWishTopicHalfScreenViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)onBtnClick:(id)arg1;
- (void)onCloseBtnClick;
- (void)layoutBtnList;
- (void)layoutTitleLabel;
- (void)layoutCloseBtn;
- (void)layoutSubviews;
- (void)initWishBtnList;
- (void)initTitleLabel;
- (void)initCloseBtn;
- (void)initSubviews;
- (id)initWithTopicItemArr:(id)arg1 bgImage:(id)arg2;

@end

