//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "MMWebImageViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "WCActionSheetDelegate-Protocol.h"
#import "WDWishProfileCellDelegate-Protocol.h"
#import "tableViewDelegate-Protocol.h"

@class CAGradientLayer, CustomVisualEffectView, MMTableView, MMUIButton, NSMutableArray, NSString, UILabel, UIView, WDWishProfileInfoOpenParams;

@interface WDWishProfileViewController : MMUIViewController <UITableViewDelegate, UITableViewDataSource, tableViewDelegate, MMWebImageViewDelegate, WDWishProfileCellDelegate, WCActionSheetDelegate>
{
    _Bool _isSelfWish;
    _Bool _hasMore;
    _Bool _isDeleting;
    CAGradientLayer *_backgroundGradientLayer;
    CustomVisualEffectView *_effectView;
    UIView *_navBarView;
    CAGradientLayer *_navBarGradientLayer;
    CustomVisualEffectView *_navBarEffectView;
    MMUIButton *_closeBtn;
    UIView *_headImgView;
    UILabel *_nicknameLabel;
    UILabel *_locationLabel;
    MMTableView *_tableView;
    UIView *_tableHeaderView;
    WDWishProfileInfoOpenParams *_openParams;
    NSMutableArray *_arrCellViewModel;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool isDeleting; // @synthesize isDeleting=_isDeleting;
@property(nonatomic) _Bool hasMore; // @synthesize hasMore=_hasMore;
@property(nonatomic) _Bool isSelfWish; // @synthesize isSelfWish=_isSelfWish;
@property(retain, nonatomic) NSMutableArray *arrCellViewModel; // @synthesize arrCellViewModel=_arrCellViewModel;
@property(retain, nonatomic) WDWishProfileInfoOpenParams *openParams; // @synthesize openParams=_openParams;
@property(retain, nonatomic) UIView *tableHeaderView; // @synthesize tableHeaderView=_tableHeaderView;
@property(retain, nonatomic) MMTableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) UILabel *locationLabel; // @synthesize locationLabel=_locationLabel;
@property(retain, nonatomic) UILabel *nicknameLabel; // @synthesize nicknameLabel=_nicknameLabel;
@property(retain, nonatomic) UIView *headImgView; // @synthesize headImgView=_headImgView;
@property(retain, nonatomic) MMUIButton *closeBtn; // @synthesize closeBtn=_closeBtn;
@property(retain, nonatomic) CustomVisualEffectView *navBarEffectView; // @synthesize navBarEffectView=_navBarEffectView;
@property(retain, nonatomic) CAGradientLayer *navBarGradientLayer; // @synthesize navBarGradientLayer=_navBarGradientLayer;
@property(retain, nonatomic) UIView *navBarView; // @synthesize navBarView=_navBarView;
@property(retain, nonatomic) CustomVisualEffectView *effectView; // @synthesize effectView=_effectView;
@property(retain, nonatomic) CAGradientLayer *backgroundGradientLayer; // @synthesize backgroundGradientLayer=_backgroundGradientLayer;
- (void)delayStartLoading;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)onDeleteWishWithId:(id)arg1;
- (void)onCellDeleteBtnClick:(id)arg1;
- (void)onCellLikeBtnClick:(id)arg1 isLike:(_Bool)arg2;
- (void)onLoadImageOK:(id)arg1;
- (void)layoutTableView;
- (void)layoutNavBar;
- (void)viewWillLayoutSubviews;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (_Bool)useTransparentNavibar;
- (void)initTableView;
- (void)onCloseBtnClick;
- (void)updateLocationLabel;
- (void)initNavBar;
- (void)initSubviews;
- (void)initCellViewModel:(id)arg1;
- (void)initData;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithParams:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

