//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CustomVisualEffectView, MMWebImageView, RichTextView, UIButton, UIImageView, UILabel, WDWishDonateInfo;
@protocol WDWishDonateTipsPageViewDelegate;

@interface WDWishDonateTipsPageView : UIView
{
    _Bool _isTransitioning;
    WDWishDonateInfo *_info;
    id <WDWishDonateTipsPageViewDelegate> _delegate;
    CustomVisualEffectView *_cardView;
    UIImageView *_imageView;
    UILabel *_titleLabel;
    RichTextView *_descLabel;
    UIButton *_linkButton;
    UIButton *_confirmBtn;
    UIView *_lineView;
    MMWebImageView *_headImgView;
    UILabel *_wishTitleLabel;
    UILabel *_wishContentLabel;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool isTransitioning; // @synthesize isTransitioning=_isTransitioning;
@property(retain, nonatomic) UILabel *wishContentLabel; // @synthesize wishContentLabel=_wishContentLabel;
@property(retain, nonatomic) UILabel *wishTitleLabel; // @synthesize wishTitleLabel=_wishTitleLabel;
@property(retain, nonatomic) MMWebImageView *headImgView; // @synthesize headImgView=_headImgView;
@property(retain, nonatomic) UIView *lineView; // @synthesize lineView=_lineView;
@property(retain, nonatomic) UIButton *confirmBtn; // @synthesize confirmBtn=_confirmBtn;
@property(retain, nonatomic) UIButton *linkButton; // @synthesize linkButton=_linkButton;
@property(retain, nonatomic) RichTextView *descLabel; // @synthesize descLabel=_descLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) CustomVisualEffectView *cardView; // @synthesize cardView=_cardView;
@property(nonatomic) __weak id <WDWishDonateTipsPageViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) WDWishDonateInfo *info; // @synthesize info=_info;
- (void)onLinkBtnClick;
- (void)onConfirmBtnClick;
- (void)layoutCardViewPos;
- (void)layoutSubviews;
- (void)dismissWithAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)show:(CDUnknownBlockType)arg1;
- (void)initSubviews;
- (id)initWithInfo:(id)arg1;

@end

