//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface WDWishProfileInfoOpenParams : NSObject
{
    NSString *_headUrl;
    NSString *_nickname;
    NSString *_username;
    NSString *_wishTicket;
    NSArray *_backgroundGradientLayerColors;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *backgroundGradientLayerColors; // @synthesize backgroundGradientLayerColors=_backgroundGradientLayerColors;
@property(retain, nonatomic) NSString *wishTicket; // @synthesize wishTicket=_wishTicket;
@property(retain, nonatomic) NSString *username; // @synthesize username=_username;
@property(retain, nonatomic) NSString *nickname; // @synthesize nickname=_nickname;
@property(retain, nonatomic) NSString *headUrl; // @synthesize headUrl=_headUrl;

@end

