//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "InputControllerDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"
#import "WCFinderLiveHalfScreenUtilControllerDelegate-Protocol.h"
#import "WDWishTopicHalfScreenViewDelegate-Protocol.h"

@class CustomVisualEffectView, EmoticonBoardView, MMGrowTextView, MMUIButton, NSMutableArray, NSString, UIImageView, WCFinderLiveHalfScreenUtilController, WCInputController, WDCommonWishInfo, WDWishEditParams;
@protocol WDWishEditViewControllerDelegate;

@interface WDWishEditViewController : MMUIViewController <UIGestureRecognizerDelegate, WDWishTopicHalfScreenViewDelegate, InputControllerDelegate, WCFinderLiveHalfScreenUtilControllerDelegate>
{
    _Bool _hasAppear;
    _Bool _isKeyboardShow;
    _Bool _hasPostSuccess;
    _Bool _isPosting;
    _Bool _showingExceedMaxLengthToast;
    id <WDWishEditViewControllerDelegate> _delegate;
    WDWishEditParams *_params;
    WDCommonWishInfo *_wishInfo;
    NSMutableArray *_topicList;
    UIImageView *_bgImageView;
    CustomVisualEffectView *_effectView;
    MMUIButton *_closeBtn;
    MMGrowTextView *_textView;
    MMUIButton *_topicWishBtn;
    MMUIButton *_confirmBtn;
    MMUIButton *_protocolBtn;
    WCInputController *_inputController;
    EmoticonBoardView *_emoticonBoardView;
    UIImageView *_inputView;
    MMUIButton *_expressionBtn;
    MMUIButton *_collapseBtn;
    WCFinderLiveHalfScreenUtilController *_verifyAndPolicyView;
    struct _NSRange _lastSelectRange;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WCFinderLiveHalfScreenUtilController *verifyAndPolicyView; // @synthesize verifyAndPolicyView=_verifyAndPolicyView;
@property(retain, nonatomic) MMUIButton *collapseBtn; // @synthesize collapseBtn=_collapseBtn;
@property(retain, nonatomic) MMUIButton *expressionBtn; // @synthesize expressionBtn=_expressionBtn;
@property(retain, nonatomic) UIImageView *inputView; // @synthesize inputView=_inputView;
@property(retain, nonatomic) EmoticonBoardView *emoticonBoardView; // @synthesize emoticonBoardView=_emoticonBoardView;
@property(retain, nonatomic) WCInputController *inputController; // @synthesize inputController=_inputController;
@property(nonatomic) struct _NSRange lastSelectRange; // @synthesize lastSelectRange=_lastSelectRange;
@property(nonatomic) _Bool showingExceedMaxLengthToast; // @synthesize showingExceedMaxLengthToast=_showingExceedMaxLengthToast;
@property(nonatomic) _Bool isPosting; // @synthesize isPosting=_isPosting;
@property(nonatomic) _Bool hasPostSuccess; // @synthesize hasPostSuccess=_hasPostSuccess;
@property(nonatomic) _Bool isKeyboardShow; // @synthesize isKeyboardShow=_isKeyboardShow;
@property(nonatomic) _Bool hasAppear; // @synthesize hasAppear=_hasAppear;
@property(retain, nonatomic) MMUIButton *protocolBtn; // @synthesize protocolBtn=_protocolBtn;
@property(retain, nonatomic) MMUIButton *confirmBtn; // @synthesize confirmBtn=_confirmBtn;
@property(retain, nonatomic) MMUIButton *topicWishBtn; // @synthesize topicWishBtn=_topicWishBtn;
@property(retain, nonatomic) MMGrowTextView *textView; // @synthesize textView=_textView;
@property(retain, nonatomic) MMUIButton *closeBtn; // @synthesize closeBtn=_closeBtn;
@property(retain, nonatomic) CustomVisualEffectView *effectView; // @synthesize effectView=_effectView;
@property(retain, nonatomic) UIImageView *bgImageView; // @synthesize bgImageView=_bgImageView;
@property(retain, nonatomic) NSMutableArray *topicList; // @synthesize topicList=_topicList;
@property(retain, nonatomic) WDCommonWishInfo *wishInfo; // @synthesize wishInfo=_wishInfo;
@property(retain, nonatomic) WDWishEditParams *params; // @synthesize params=_params;
@property(nonatomic) __weak id <WDWishEditViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)mmNavigationController:(id)arg1 animationControllerForOperation:(long long)arg2 fromViewController:(id)arg3 toViewController:(id)arg4;
- (void)onWCFinderLiveHalfScreenConfirmButtonClicked:(long long)arg1;
- (void)onShowLiveVerifyHalfScreenView;
- (void)onPostWishComplete:(_Bool)arg1 resp:(id)arg2;
- (id)parseTopicFromContent:(id)arg1;
- (void)delayStartLoading;
- (void)onConfirmBtnClick;
- (void)checkAndUpdateConfirmBtnStatus;
- (void)keyboardDidHide;
- (void)keyboardWillShow;
- (void)didCommitText:(id)arg1;
- (_Bool)showErrorToastWithText:(id)arg1;
- (void)textViewTextDidExceedMaxLength;
- (void)textViewTextDidChange;
- (double)getVisibleHeight;
- (void)onTopItemSelected:(id)arg1;
- (void)insertStringToTextView:(id)arg1 showToastExceed:(_Bool)arg2;
- (void)onTopicWishBtnClick;
- (void)onCollapseBtnClicked;
- (void)onExpressionBtnClicked:(id)arg1;
- (void)onProtocolBtnClick;
- (void)onCloseBtnClick;
- (void)onTapSelf:(id)arg1;
- (void)endEdit;
- (void)beginEdit;
- (void)layoutInputToolView;
- (void)layoutSelectArea;
- (void)layoutTextView;
- (void)layoutNavbar;
- (void)layoutBgView;
- (void)layoutSubviews;
- (void)viewWillLayoutSubviews;
- (void)initSelectArea;
- (void)initInputToolView;
- (void)initTextView;
- (void)initNavBar;
- (void)initBgView;
- (void)initSubviews;
- (void)initData;
- (void)viewDidBePoped:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillDisappear:(_Bool)arg1;
- (_Bool)useTransparentNavibar;
- (void)dealloc;
- (id)initWithParams:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

