//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, UIImageView, UILabel;

@interface WDWishToastView : UIView
{
    NSString *_text;
    id _context;
    UILabel *_textLabel;
    UIImageView *_arrowView;
    CDUnknownBlockType _clickCallback;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType clickCallback; // @synthesize clickCallback=_clickCallback;
@property(retain, nonatomic) UIImageView *arrowView; // @synthesize arrowView=_arrowView;
@property(retain, nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;
@property(retain, nonatomic) id context; // @synthesize context=_context;
@property(retain, nonatomic) NSString *text; // @synthesize text=_text;
- (void)onTap;
- (void)layoutSubviews;
- (void)hideWithAnimated:(_Bool)arg1;
- (void)hideWithAnimation;
- (void)showWithSuperView:(id)arg1 forDuration:(double)arg2 clickCallback:(CDUnknownBlockType)arg3;
- (void)showWithSuperView:(id)arg1;
- (double)maxWidth;
- (void)initArrowImgView;
- (void)initTextLabel;
- (void)initSubviews;
- (void)dealloc;
- (id)init;

@end

