//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUserService.h"

#import "IVOIPUILogicMgrExt-Protocol.h"
#import "MMServiceProtocol-Protocol.h"
#import "MultiTalkMgrExt-Protocol.h"
#import "PBMessageObserverDelegate-Protocol.h"

@class FestivalWishConfig, MMTimer, MemoryMappedKV, NSArray, NSData, NSMutableArray, NSMutableDictionary, NSMutableSet, NSString, UIImage, UIView, WDCommonWishInfo, WDHomeViewController;

@interface WeDrawManager : MMUserService <PBMessageObserverDelegate, MultiTalkMgrExt, IVOIPUILogicMgrExt, MMServiceProtocol>
{
    _Bool _isLive;
    _Bool _bFestivalWishInitReady;
    _Bool _isFloatWindow;
    _Bool _waitingHeartBeat;
    unsigned int _heartBeatInterval;
    NSArray *_titlePollWording;
    MemoryMappedKV *_mappedKV;
    MMTimer *_timer;
    FestivalWishConfig *_config;
    NSData *_wishContext;
    NSArray *_recommentWishes;
    NSMutableArray *_recommentCaches;
    long long _cacheIndex;
    NSMutableArray *_displayUsers;
    NSMutableArray *_topicList;
    WDCommonWishInfo *_myWish;
    NSMutableDictionary *_friendWishList;
    NSString *_dataUrl;
    NSMutableArray *_musicList;
    NSMutableSet *_hasWishUsers;
    NSMutableDictionary *_profileContexts;
    NSMutableDictionary *_hashFriends;
    NSString *_myHashName;
    NSMutableDictionary *_liveEncFriends;
    UIImage *_canvasCacheImage;
    WDHomeViewController *_homeVC;
    UIView *_containerView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) WDHomeViewController *homeVC; // @synthesize homeVC=_homeVC;
@property(retain, nonatomic) UIImage *canvasCacheImage; // @synthesize canvasCacheImage=_canvasCacheImage;
@property(retain, nonatomic) NSMutableDictionary *liveEncFriends; // @synthesize liveEncFriends=_liveEncFriends;
@property(retain, nonatomic) NSString *myHashName; // @synthesize myHashName=_myHashName;
@property(retain, nonatomic) NSMutableDictionary *hashFriends; // @synthesize hashFriends=_hashFriends;
@property(retain, nonatomic) NSMutableDictionary *profileContexts; // @synthesize profileContexts=_profileContexts;
@property(nonatomic) _Bool waitingHeartBeat; // @synthesize waitingHeartBeat=_waitingHeartBeat;
@property(retain, nonatomic) NSMutableSet *hasWishUsers; // @synthesize hasWishUsers=_hasWishUsers;
@property(retain, nonatomic) NSMutableArray *musicList; // @synthesize musicList=_musicList;
@property(retain, nonatomic) NSString *dataUrl; // @synthesize dataUrl=_dataUrl;
@property(retain, nonatomic) NSMutableDictionary *friendWishList; // @synthesize friendWishList=_friendWishList;
@property(retain, nonatomic) WDCommonWishInfo *myWish; // @synthesize myWish=_myWish;
@property(retain, nonatomic) NSMutableArray *topicList; // @synthesize topicList=_topicList;
@property(retain, nonatomic) NSMutableArray *displayUsers; // @synthesize displayUsers=_displayUsers;
@property(nonatomic) long long cacheIndex; // @synthesize cacheIndex=_cacheIndex;
@property(retain, nonatomic) NSMutableArray *recommentCaches; // @synthesize recommentCaches=_recommentCaches;
@property(retain, nonatomic) NSArray *recommentWishes; // @synthesize recommentWishes=_recommentWishes;
@property(retain, nonatomic) NSData *wishContext; // @synthesize wishContext=_wishContext;
@property(retain, nonatomic) FestivalWishConfig *config; // @synthesize config=_config;
@property(nonatomic) unsigned int heartBeatInterval; // @synthesize heartBeatInterval=_heartBeatInterval;
@property(nonatomic) _Bool isFloatWindow; // @synthesize isFloatWindow=_isFloatWindow;
@property(nonatomic) _Bool bFestivalWishInitReady; // @synthesize bFestivalWishInitReady=_bFestivalWishInitReady;
@property(retain, nonatomic) MMTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) MemoryMappedKV *mappedKV; // @synthesize mappedKV=_mappedKV;
@property(retain, nonatomic) NSArray *titlePollWording; // @synthesize titlePollWording=_titlePollWording;
- (void)onVideoVoipViewDidAppear:(id)arg1;
- (void)onBeginMultiTalk;
- (void)setBGMDebugOpen:(_Bool)arg1;
- (_Bool)isBGMDebugOpen;
- (void)setBGMOpen:(_Bool)arg1;
- (_Bool)isBGMOpen;
- (void)clearTmpData;
- (void)clearMMKV;
- (void)clearLocalData:(CDUnknownBlockType)arg1;
- (_Bool)exitFloatWindow;
- (_Bool)enterFloatWindow;
- (_Bool)isMyUserName:(id)arg1;
- (id)getFriendUserName:(id)arg1;
- (_Bool)isFriendUserName:(id)arg1;
- (void)markAgreeProtocol;
- (_Bool)hasAgreeProtocol;
- (unsigned int)getCurrentDay;
- (void)updateQuotaWithConfig:(id)arg1;
- (void)updateWishQuotaAfterMakeWish;
- (unsigned int)getWishLeftQuota;
- (void)markFinshMakeWish;
- (_Bool)hasFinishMakeWish;
- (void)markFinishShowStateGuide;
- (_Bool)hasShowStateGuide;
- (void)markShowIntroView;
- (_Bool)hasShowIntroView;
- (id)loadCacheCanvasImage;
- (void)releaseCacheCanvasImage;
- (void)scheduleReleaseCacheCanvasImage;
- (void)cancelLastScheduleReleaseCacheCanvasImage;
- (void)saveCacheCanvasImage:(id)arg1;
- (void)setCanvasImageSourceType:(unsigned int)arg1;
- (unsigned int)canvasImageSouceType;
- (void)setInterpolationType:(unsigned int)arg1;
- (unsigned int)interpolationType;
- (void)setEntryType:(unsigned int)arg1;
- (unsigned int)entryType;
- (void)setConfigToCache:(id)arg1;
- (id)configFromCache;
- (void)setCanvasSize:(unsigned int)arg1;
- (unsigned int)canvasSize;
- (void)setDebugMode:(_Bool)arg1;
- (_Bool)isDebugMode;
- (id)getMyLastWish;
- (id)getAllMyWishes;
- (long long)getWishFriendCount;
- (id)getAllFriendAndMyWishes;
- (void)getRandomWishElement:(CDUnknownBlockType)arg1;
- (id)getAllWishElements;
- (id)getTopicList;
- (id)getLikeMessages;
- (id)getKVWishContext;
- (void)setKVWishContext:(id)arg1;
- (unsigned int)getLastViewLikeTime;
- (void)setLastViewLikeTime:(unsigned int)arg1;
- (_Bool)isUserHasWish:(id)arg1;
- (_Bool)isMyLikeWish:(id)arg1;
- (_Bool)isMyWish:(id)arg1;
- (id)genMyWishWithEmptyContent;
- (id)genWish:(id)arg1 x:(long long)arg2 y:(long long)arg3 action:(unsigned int)arg4;
- (void)getWishInViewport:(struct CGPoint)arg1 offset:(long long)arg2 complete:(CDUnknownBlockType)arg3;
- (void)getWishArrayByX:(long long)arg1 y:(long long)arg2 complete:(CDUnknownBlockType)arg3;
- (id)getMyWishByWishId:(id)arg1;
- (_Bool)getWishByWishId:(id)arg1 complete:(CDUnknownBlockType)arg2;
- (void)requestWishByWishId:(id)arg1 userData:(id)arg2;
- (void)batchGetWish:(id)arg1 complete:(CDUnknownBlockType)arg2;
- (void)getProfile:(id)arg1 complete:(CDUnknownBlockType)arg2;
- (void)likeWish:(id)arg1 isLike:(_Bool)arg2 complete:(CDUnknownBlockType)arg3;
- (void)deleteWish:(id)arg1 complete:(CDUnknownBlockType)arg2;
- (void)postWish:(id)arg1 complete:(CDUnknownBlockType)arg2;
- (void)processBatchGetWishes:(id)arg1;
- (void)processFetchProfile:(id)arg1;
- (id)getFestivalWishConfig;
- (void)processFetchWishList:(id)arg1;
- (void)processFetchWish:(id)arg1;
- (void)processLikeWish:(id)arg1;
- (void)processPostWish:(id)arg1;
- (void)deleteFriendCacheWishInfoByID:(id)arg1;
- (void)processWishHeartBeat:(id)arg1;
- (void)onTimerCallback;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (id)getLastWCFinderDataItemTid;
- (void)removeLastWCFinderDataItemTid;
- (void)markLastWCFinderDataItemTid:(id)arg1;
- (unsigned int)getLastVisitTime;
- (void)markLastVisitTime:(unsigned int)arg1;
- (void)stopLive;
- (void)startLive;
- (_Bool)isLive;
- (void)stopHeartBeat;
- (void)beginHeartBeatWithInterval:(double)arg1;
- (void)requestHeartBeat:(_Bool)arg1 scene:(unsigned int)arg2;
- (void)beginHeartBeat:(unsigned int)arg1;
- (id)getFestivalLiveInfo:(unsigned int)arg1 callback:(CDUnknownBlockType)arg2;
- (void)dealloc;
- (_Bool)isForbided:(unsigned int)arg1;
- (void)unregisterAllExt;
- (void)registerAllExt;
- (void)onServiceClearData;
- (void)onServiceInit;
- (void)onEnterMinimizedTask:(id)arg1 openContext:(id)arg2 taskEnterScene:(unsigned int)arg3;
- (void)onContainerViewCloseBtnClick;
- (void)onContainerViewFullBtnClick;
- (id)getContainerView;
- (id)genTaskContainerInfo;
- (id)genTaskData;
- (void)tryRemoveMinimizeTask;
- (void)minimizeHomeViewController:(id)arg1;
- (id)getHomeViewController;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

