//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WSReportBaseItem.h"

@class NSString;

@interface WSGlobalSearchVertEntryReporter : WSReportBaseItem
{
    unsigned int _actionTimeStamp;
    NSString *_sessionID;
    unsigned long long _action;
    unsigned long long _businessType;
    long long _position;
    NSString *_content;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned int actionTimeStamp; // @synthesize actionTimeStamp=_actionTimeStamp;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
@property(nonatomic) long long position; // @synthesize position=_position;
@property(nonatomic) unsigned long long businessType; // @synthesize businessType=_businessType;
@property(nonatomic) unsigned long long action; // @synthesize action=_action;
@property(copy, nonatomic) NSString *sessionID; // @synthesize sessionID=_sessionID;
- (unsigned int)reportKvId;
- (id)reportOrderedFieldNameArr;

@end

